package erpfms.modelfms.fmsvo;

import erpglobals.modelglobals.ERPViewObjectImpl;

import java.sql.Timestamp;

import oracle.jbo.domain.Date;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 17 20:26:21 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlBudgetVOImpl extends ERPViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GlBudgetVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_BUDGET_SNO.
     * @return variable value for P_ADF_BUDGET_SNO
     */
    public Integer getP_ADF_BUDGET_SNO() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_BUDGET_SNO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_BUDGET_SNO.
     * @param value value to bind as P_ADF_BUDGET_SNO
     */
    public void setP_ADF_BUDGET_SNO(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_BUDGET_SNO", value);
    }

    /**
     * Returns the variable value for P_ADF_COMPANY_ID.
     * @return variable value for P_ADF_COMPANY_ID
     */
    public Integer getP_ADF_COMPANY_ID() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_COMPANY_ID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_COMPANY_ID.
     * @param value value to bind as P_ADF_COMPANY_ID
     */
    public void setP_ADF_COMPANY_ID(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_COMPANY_ID", value);
    }
    @Override 
    public void afterRollback(TransactionEvent transactionEvent) {
        // TODO Implement this method
        super.afterRollback(transactionEvent);
        setErpPkColumn("BudgetSno");
        setErpParameterId("P_ADF_BUDGET_SNO");
        setErpViewObjectName("GlBudgetByBudgetIdCRUD");
    }

    /**
     * Returns the variable value for P_ADF_DATE.
     * @return variable value for P_ADF_DATE
     */
    public Date getP_ADF_DATE() {
        return (Date) ensureVariableManager().getVariableValue("P_ADF_DATE");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_DATE.
     * @param value value to bind as P_ADF_DATE
     */
    public void setP_ADF_DATE(Date value) {
        ensureVariableManager().setVariableValue("P_ADF_DATE", value);
    }
    @Override
    public void executeQuery() {
        // TODO Implement this method
        System.out.println(getWhereClause());
        System.out.println(getWhereClauseParams());
        super.executeQuery();
    }
}

