package erpfms.modelfms.fmsvo;

import erpfms.modelfms.fmseo.GlChartOfAccountsImpl;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 01 20:49:14 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlChartOfAccountsVORowImpl extends ViewRowImpl {


    public static final int ENTITY_GLCHARTOFACCOUNTS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ChartOfAccountId,
        ChartOfAccountCode,
        Description,
        ParentChartOfAccountId,
        CoaTypeSno,
        IsActive,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        CompanyId,
        GlobalCompanyId,
        LevelNo,
        txtParentCOACode,
        txtParentCOADescription,
        txtParentCOALevel,
        txtTest,
        CoaHierarchyPath,
        txtParentHierarchyPath,
        ParentChartOfAccountIdGlChartOfAccountsVO,
        GlChartOfAccountsVO,
        GlVoucherLinesVO,
        GlBankVO,
        GlBankBranchVO,
        GlParameterVO,
        AccSysGeneralValueVO,
        AccGlCoaTypeVO,
        AccGlChartOfAccountsVO,
        AccGlParameterVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CHARTOFACCOUNTID = AttributesEnum.ChartOfAccountId.index();
    public static final int CHARTOFACCOUNTCODE = AttributesEnum.ChartOfAccountCode.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int PARENTCHARTOFACCOUNTID = AttributesEnum.ParentChartOfAccountId.index();
    public static final int COATYPESNO = AttributesEnum.CoaTypeSno.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int LEVELNO = AttributesEnum.LevelNo.index();
    public static final int TXTPARENTCOACODE = AttributesEnum.txtParentCOACode.index();
    public static final int TXTPARENTCOADESCRIPTION = AttributesEnum.txtParentCOADescription.index();
    public static final int TXTPARENTCOALEVEL = AttributesEnum.txtParentCOALevel.index();
    public static final int TXTTEST = AttributesEnum.txtTest.index();
    public static final int COAHIERARCHYPATH = AttributesEnum.CoaHierarchyPath.index();
    public static final int TXTPARENTHIERARCHYPATH = AttributesEnum.txtParentHierarchyPath.index();
    public static final int PARENTCHARTOFACCOUNTIDGLCHARTOFACCOUNTSVO =
        AttributesEnum.ParentChartOfAccountIdGlChartOfAccountsVO.index();
    public static final int GLCHARTOFACCOUNTSVO = AttributesEnum.GlChartOfAccountsVO.index();
    public static final int GLVOUCHERLINESVO = AttributesEnum.GlVoucherLinesVO.index();
    public static final int GLBANKVO = AttributesEnum.GlBankVO.index();
    public static final int GLBANKBRANCHVO = AttributesEnum.GlBankBranchVO.index();
    public static final int GLPARAMETERVO = AttributesEnum.GlParameterVO.index();
    public static final int ACCSYSGENERALVALUEVO = AttributesEnum.AccSysGeneralValueVO.index();
    public static final int ACCGLCOATYPEVO = AttributesEnum.AccGlCoaTypeVO.index();
    public static final int ACCGLCHARTOFACCOUNTSVO = AttributesEnum.AccGlChartOfAccountsVO.index();
    public static final int ACCGLPARAMETERVO = AttributesEnum.AccGlParameterVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlChartOfAccountsVORowImpl() {
    }

    /**
     * Gets GlChartOfAccounts entity object.
     * @return the GlChartOfAccounts
     */
    public GlChartOfAccountsImpl getGlChartOfAccounts() {
        return (GlChartOfAccountsImpl) getEntity(ENTITY_GLCHARTOFACCOUNTS);
    }

    /**
     * Gets the attribute value for CHART_OF_ACCOUNT_ID using the alias name ChartOfAccountId.
     * @return the CHART_OF_ACCOUNT_ID
     */
    public Integer getChartOfAccountId() {
        return (Integer) getAttributeInternal(CHARTOFACCOUNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CHART_OF_ACCOUNT_ID using the alias name ChartOfAccountId.
     * @param value value to set the CHART_OF_ACCOUNT_ID
     */
    public void setChartOfAccountId(Integer value) {
        setAttributeInternal(CHARTOFACCOUNTID, value);
    }

    /**
     * Gets the attribute value for CHART_OF_ACCOUNT_CODE using the alias name ChartOfAccountCode.
     * @return the CHART_OF_ACCOUNT_CODE
     */
    public String getChartOfAccountCode() {
        return (String) getAttributeInternal(CHARTOFACCOUNTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CHART_OF_ACCOUNT_CODE using the alias name ChartOfAccountCode.
     * @param value value to set the CHART_OF_ACCOUNT_CODE
     */
    public void setChartOfAccountCode(String value) {
        setAttributeInternal(CHARTOFACCOUNTCODE, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for PARENT_CHART_OF_ACCOUNT_ID using the alias name ParentChartOfAccountId.
     * @return the PARENT_CHART_OF_ACCOUNT_ID
     */
    public Integer getParentChartOfAccountId() {
        return (Integer) getAttributeInternal(PARENTCHARTOFACCOUNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_CHART_OF_ACCOUNT_ID using the alias name ParentChartOfAccountId.
     * @param value value to set the PARENT_CHART_OF_ACCOUNT_ID
     */
    public void setParentChartOfAccountId(Integer value) {
        setAttributeInternal(PARENTCHARTOFACCOUNTID, value);
    }

    /**
     * Gets the attribute value for COA_TYPE_SNO using the alias name CoaTypeSno.
     * @return the COA_TYPE_SNO
     */
    public Integer getCoaTypeSno() {
        return (Integer) getAttributeInternal(COATYPESNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_TYPE_SNO using the alias name CoaTypeSno.
     * @param value value to set the COA_TYPE_SNO
     */
    public void setCoaTypeSno(Integer value) {
        setAttributeInternal(COATYPESNO, value);
        getAccGlParameterVO().executeQuery();
        
        
        getAccGlChartOfAccountsVO().setNamedWhereClauseParam("P_ADF_COMPANY_ID", getCompanyId());
        getAccGlChartOfAccountsVO().setNamedWhereClauseParam("P_ADF_GLOBAL_COMPANY_ID", getGlobalCompanyId());
        getAccGlChartOfAccountsVO().setNamedWhereClauseParam("P_ADF_LEVEL_NO", getAccGlParameterVO().getRowCount()==0?0:Integer.parseInt(getAccGlParameterVO().first().getAttribute("ParameterValue").toString())-1);
        getAccGlChartOfAccountsVO().setNamedWhereClauseParam("P_ADF_COA_TYPE_SNO", value);
        getAccGlChartOfAccountsVO().executeQuery();
        //System.out.println(getAccGlChartOfAccountsVO().getRowCount()+ " get rcount");
    }

    /**
     * Gets the attribute value for IS_ACTIVE using the alias name IsActive.
     * @return the IS_ACTIVE
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_ACTIVE using the alias name IsActive.
     * @param value value to set the IS_ACTIVE
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID using the alias name CompanyId.
     * @return the COMPANY_ID
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID using the alias name CompanyId.
     * @param value value to set the COMPANY_ID
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @return the GLOBAL_COMPANY_ID
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @param value value to set the GLOBAL_COMPANY_ID
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for LEVEL_NO using the alias name LevelNo.
     * @return the LEVEL_NO
     */
    public Integer getLevelNo() {
        return (Integer) getAttributeInternal(LEVELNO);
    }

    /**
     * Sets <code>value</code> as attribute value for LEVEL_NO using the alias name LevelNo.
     * @param value value to set the LEVEL_NO
     */
    public void setLevelNo(Integer value) {
        setAttributeInternal(LEVELNO, value);
    }

    /**
     * Gets the attribute value for TXT_PARENT_COACODE using the alias name txtParentCOACode.
     * @return the TXT_PARENT_COACODE
     */
    public String gettxtParentCOACode() {
        return (String) getAttributeInternal(TXTPARENTCOACODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PARENT_COACODE using the alias name txtParentCOACode.
     * @param value value to set the TXT_PARENT_COACODE
     */
    public void settxtParentCOACode(String value) {
        setAttributeInternal(TXTPARENTCOACODE, value);
    }

    /**
     * Gets the attribute value for TXT_PARENT_COADESCRIPTION using the alias name txtParentCOADescription.
     * @return the TXT_PARENT_COADESCRIPTION
     */
    public String gettxtParentCOADescription() {
        return (String) getAttributeInternal(TXTPARENTCOADESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PARENT_COADESCRIPTION using the alias name txtParentCOADescription.
     * @param value value to set the TXT_PARENT_COADESCRIPTION
     */
    public void settxtParentCOADescription(String value) {
        setAttributeInternal(TXTPARENTCOADESCRIPTION, value);
    }

    /**
     * Gets the attribute value for TXT_PARENT_COALEVEL using the alias name txtParentCOALevel.
     * @return the TXT_PARENT_COALEVEL
     */
    public Integer gettxtParentCOALevel() {
        return (Integer) getAttributeInternal(TXTPARENTCOALEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PARENT_COALEVEL using the alias name txtParentCOALevel.
     * @param value value to set the TXT_PARENT_COALEVEL
     */
    public void settxtParentCOALevel(Integer value) {
        setAttributeInternal(TXTPARENTCOALEVEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtTest.
     * @return the txtTest
     */
    public String gettxtTest() {
        return (String) getAttributeInternal(TXTTEST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtTest.
     * @param value value to set the  txtTest
     */
    public void settxtTest(String value) {
        setAttributeInternal(TXTTEST, value);
    }

    /**
     * Gets the attribute value for COA_HIERARCHY_PATH using the alias name CoaHierarchyPath.
     * @return the COA_HIERARCHY_PATH
     */
    public String getCoaHierarchyPath() {
        return (String) getAttributeInternal(COAHIERARCHYPATH);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_HIERARCHY_PATH using the alias name CoaHierarchyPath.
     * @param value value to set the COA_HIERARCHY_PATH
     */
    public void setCoaHierarchyPath(String value) {
        setAttributeInternal(COAHIERARCHYPATH, value);
    }

    /**
     * Gets the attribute value for TXT_PARENT_HIERARCHY_PATH using the alias name txtParentHierarchyPath.
     * @return the TXT_PARENT_HIERARCHY_PATH
     */
    public String gettxtParentHierarchyPath() {
        return (String) getAttributeInternal(TXTPARENTHIERARCHYPATH);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PARENT_HIERARCHY_PATH using the alias name txtParentHierarchyPath.
     * @param value value to set the TXT_PARENT_HIERARCHY_PATH
     */
    public void settxtParentHierarchyPath(String value) {
        setAttributeInternal(TXTPARENTHIERARCHYPATH, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ParentChartOfAccountIdGlChartOfAccountsVO.
     */
    public Row getParentChartOfAccountIdGlChartOfAccountsVO() {
        return (Row) getAttributeInternal(PARENTCHARTOFACCOUNTIDGLCHARTOFACCOUNTSVO);
    }

    /**
     * Sets the master-detail link ParentChartOfAccountIdGlChartOfAccountsVO between this object and <code>value</code>.
     */
    public void setParentChartOfAccountIdGlChartOfAccountsVO(Row value) {
        setAttributeInternal(PARENTCHARTOFACCOUNTIDGLCHARTOFACCOUNTSVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GlChartOfAccountsVO.
     */
    public RowIterator getGlChartOfAccountsVO() {
        return (RowIterator) getAttributeInternal(GLCHARTOFACCOUNTSVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GlVoucherLinesVO.
     */
    public RowIterator getGlVoucherLinesVO() {
        return (RowIterator) getAttributeInternal(GLVOUCHERLINESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GlBankVO.
     */
    public RowIterator getGlBankVO() {
        return (RowIterator) getAttributeInternal(GLBANKVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GlBankBranchVO.
     */
    public RowIterator getGlBankBranchVO() {
        return (RowIterator) getAttributeInternal(GLBANKBRANCHVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlParameterVO.
     */
    public Row getGlParameterVO() {
        return (Row) getAttributeInternal(GLPARAMETERVO);
    }

    /**
     * Sets the master-detail link GlParameterVO between this object and <code>value</code>.
     */
    public void setGlParameterVO(Row value) {
        setAttributeInternal(GLPARAMETERVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysGeneralValueVO.
     */
    public RowSet getAccSysGeneralValueVO() {
        return (RowSet) getAttributeInternal(ACCSYSGENERALVALUEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlCoaTypeVO.
     */
    public RowSet getAccGlCoaTypeVO() {
        return (RowSet) getAttributeInternal(ACCGLCOATYPEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlChartOfAccountsVO.
     */
    public RowSet getAccGlChartOfAccountsVO() {
        return (RowSet) getAttributeInternal(ACCGLCHARTOFACCOUNTSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlParameterVO.
     */
    public RowSet getAccGlParameterVO() {
        return (RowSet) getAttributeInternal(ACCGLPARAMETERVO);
    }
}

