package erpfms.modelfms.fmsvo;

import erpglobals.modelglobals.ERPViewObjectImpl;

import oracle.jbo.ViewObject;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 15 00:23:48 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlChartOfAccountsVOImpl extends ERPViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GlChartOfAccountsVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_GLOBAL_COMPANY_ID.
     * @return variable value for P_ADF_GLOBAL_COMPANY_ID
     */
    public Integer getP_ADF_GLOBAL_COMPANY_ID() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_GLOBAL_COMPANY_ID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_GLOBAL_COMPANY_ID.
     * @param value value to bind as P_ADF_GLOBAL_COMPANY_ID
     */
    public void setP_ADF_GLOBAL_COMPANY_ID(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_GLOBAL_COMPANY_ID", value);
    }

    /**
     * Returns the variable value for P_ADF_COMPANY_ID.
     * @return variable value for P_ADF_COMPANY_ID
     */
    public Integer getP_ADF_COMPANY_ID() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_COMPANY_ID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_COMPANY_ID.
     * @param value value to bind as P_ADF_COMPANY_ID
     */
    public void setP_ADF_COMPANY_ID(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_COMPANY_ID", value);
    }

    /**
     * Returns the variable value for P_ADF_COA_TYPE_SNO.
     * @return variable value for P_ADF_COA_TYPE_SNO
     */
    public Integer getP_ADF_COA_TYPE_SNO() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_COA_TYPE_SNO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_COA_TYPE_SNO.
     * @param value value to bind as P_ADF_COA_TYPE_SNO
     */
    public void setP_ADF_COA_TYPE_SNO(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_COA_TYPE_SNO", value);
    }

    /**
     * Returns the variable value for P_ADF_LEVEL_NO.
     * @return variable value for P_ADF_LEVEL_NO
     */
    public Integer getP_ADF_LEVEL_NO() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_LEVEL_NO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_LEVEL_NO.
     * @param value value to bind as P_ADF_LEVEL_NO
     */
    public void setP_ADF_LEVEL_NO(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_LEVEL_NO", value);
    }

    /**
     * Returns the variable value for P_ADF_COA_ID.
     * @return variable value for P_ADF_COA_ID
     */
    public Integer getP_ADF_COA_ID() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_COA_ID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_COA_ID.
     * @param value value to bind as P_ADF_COA_ID
     */
    public void setP_ADF_COA_ID(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_COA_ID", value);
    }


    @Override
    public void afterRollback(TransactionEvent transactionEvent) {
        // TODO Implement this method
        setErpViewObjectName("GlChartOfAccountsByCOIDCRUD");
        setErpPkColumn("ChartOfAccountId");
        setErpParameterId("P_ADF_COA_ID");
        super.afterRollback(transactionEvent);
    }


}
