package erpfms.modelfms.fmsvo;

import erpglobals.modelglobals.ERPViewRowImpl;

import java.sql.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 08 11:09:20 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlCoaUserCompanyVORowImpl extends ERPViewRowImpl {


    public static final int ENTITY_GLCOAUSERCOMPANY = 0;
    public static final int ENTITY_SYSUSERS = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CoaUserCompanySno,
        CompanyId,
        GlobalCompanyId,
        IsActive,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        UserId,
        txtGetEntityState,
        txtGetMaxEntityState,
        txtGetMinEntityState,
        UserName,
        UserIdMast,
        UserCode,
        Email,
        MobileNo,
        SysUsersVO,
        AccSysUsersVO,
        AccSysGeneralValueVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COAUSERCOMPANYSNO = AttributesEnum.CoaUserCompanySno.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int TXTGETENTITYSTATE = AttributesEnum.txtGetEntityState.index();
    public static final int TXTGETMAXENTITYSTATE = AttributesEnum.txtGetMaxEntityState.index();
    public static final int TXTGETMINENTITYSTATE = AttributesEnum.txtGetMinEntityState.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int USERIDMAST = AttributesEnum.UserIdMast.index();
    public static final int USERCODE = AttributesEnum.UserCode.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int SYSUSERSVO = AttributesEnum.SysUsersVO.index();
    public static final int ACCSYSUSERSVO = AttributesEnum.AccSysUsersVO.index();
    public static final int ACCSYSGENERALVALUEVO = AttributesEnum.AccSysGeneralValueVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlCoaUserCompanyVORowImpl() {
    }
    
    @Override
    public byte ERPdoGetEntityState() {
        // TODO Implement this method
        return super.ERPdoGetEntityState();
    }
}

