package erpfms.modelfms.fmsvo;

import erpfms.modelfms.fmseo.GlFiscalYearImpl;

import erpfms.modelfms.fmsvo.common.GlFiscalYearVORow;

import erpglobals.modelglobals.ERPViewRowImpl;

import java.sql.Timestamp;

import java.text.SimpleDateFormat;

import java.util.Calendar;
import java.util.Date;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 29 23:32:29 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlFiscalYearVORowImpl extends ERPViewRowImpl implements GlFiscalYearVORow {


    public static final int ENTITY_GLFISCALYEAR = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FiscalYearSno,
        YearDescription,
        IsActive,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        StartDate,
        EndDate,
        CompanyId,
        GlobalCompanyId,
        IsSupervised,
        SupervisedDate,
        IsUnsupervised,
        UnSupervisedDate,
        FiscalYearr,
        FiscalYearCode,
        UnSupervisedBy,
        SupervisedBy,
        GlPeriodsVO,
        AccSysGeneralValueVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FISCALYEARSNO = AttributesEnum.FiscalYearSno.index();
    public static final int YEARDESCRIPTION = AttributesEnum.YearDescription.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int FISCALYEARR = AttributesEnum.FiscalYearr.index();
    public static final int FISCALYEARCODE = AttributesEnum.FiscalYearCode.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int GLPERIODSVO = AttributesEnum.GlPeriodsVO.index();
    public static final int ACCSYSGENERALVALUEVO = AttributesEnum.AccSysGeneralValueVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlFiscalYearVORowImpl() {
    }

    /**
     * Gets GlFiscalYear entity object.
     * @return the GlFiscalYear
     */
    public GlFiscalYearImpl getGlFiscalYear() {
        return (GlFiscalYearImpl) getEntity(ENTITY_GLFISCALYEAR);
    }

    /**
     * Gets the attribute value for FISCAL_YEAR_SNO using the alias name FiscalYearSno.
     * @return the FISCAL_YEAR_SNO
     */
    public Integer getFiscalYearSno() {
        return (Integer) getAttributeInternal(FISCALYEARSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for FISCAL_YEAR_SNO using the alias name FiscalYearSno.
     * @param value value to set the FISCAL_YEAR_SNO
     */
    public void setFiscalYearSno(Integer value) {
        setAttributeInternal(FISCALYEARSNO, value);
    }

    /**
     * Gets the attribute value for YEAR_DESCRIPTION using the alias name YearDescription.
     * @return the YEAR_DESCRIPTION
     */
    public String getYearDescription() {
        return (String) getAttributeInternal(YEARDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for YEAR_DESCRIPTION using the alias name YearDescription.
     * @param value value to set the YEAR_DESCRIPTION
     */
    public void setYearDescription(String value) {
        setAttributeInternal(YEARDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for IS_ACTIVE using the alias name IsActive.
     * @return the IS_ACTIVE
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_ACTIVE using the alias name IsActive.
     * @param value value to set the IS_ACTIVE
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Timestamp getStartDate() {
        return (Timestamp) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Timestamp value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Timestamp value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID using the alias name CompanyId.
     * @return the COMPANY_ID
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID using the alias name CompanyId.
     * @param value value to set the COMPANY_ID
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @return the GLOBAL_COMPANY_ID
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @param value value to set the GLOBAL_COMPANY_ID
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @return the IS_SUPERVISED
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @param value value to set the IS_SUPERVISED
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @return the SUPERVISED_DATE
     */
    public Timestamp getSupervisedDate() {
        return (Timestamp) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @param value value to set the SUPERVISED_DATE
     */
    public void setSupervisedDate(Timestamp value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @return the IS_UNSUPERVISED
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @param value value to set the IS_UNSUPERVISED
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @return the UN_SUPERVISED_DATE
     */
    public Timestamp getUnSupervisedDate() {
        return (Timestamp) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @param value value to set the UN_SUPERVISED_DATE
     */
    public void setUnSupervisedDate(Timestamp value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for FISCAL_YEARR using the alias name FiscalYearr.
     * @return the FISCAL_YEARR
     */
    public Integer getFiscalYearr() {
        return (Integer) getAttributeInternal(FISCALYEARR);
    }

    /**
     * Sets <code>value</code> as attribute value for FISCAL_YEARR using the alias name FiscalYearr.
     * @param value value to set the FISCAL_YEARR
     */
    public void setFiscalYearr(Integer value) {
        setAttributeInternal(FISCALYEARR, value);
    }

    /**
     * Gets the attribute value for FISCAL_YEAR_CODE using the alias name FiscalYearCode.
     * @return the FISCAL_YEAR_CODE
     */
    public Integer getFiscalYearCode() {
        return (Integer) getAttributeInternal(FISCALYEARCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for FISCAL_YEAR_CODE using the alias name FiscalYearCode.
     * @param value value to set the FISCAL_YEAR_CODE
     */
    public void setFiscalYearCode(Integer value) {
        setAttributeInternal(FISCALYEARCODE, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @return the UN_SUPERVISED_BY
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @param value value to set the UN_SUPERVISED_BY
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @return the SUPERVISED_BY
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @param value value to set the SUPERVISED_BY
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GlPeriodsVO.
     */
    public RowIterator getGlPeriodsVO() {
        return (RowIterator) getAttributeInternal(GLPERIODSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysGeneralValueVO.
     */
    public RowSet getAccSysGeneralValueVO() {
        return (RowSet) getAttributeInternal(ACCSYSGENERALVALUEVO);
    }

    public void doErpGenerateFYPeriods() {
        while(getGlPeriodsVO().getRowCount()>0) {
            getGlPeriodsVO().first().remove();
        }//deleting existing rows
            Integer periodno=1;
        for (int i = 0; i < 12; i++) {
            Row r = getGlPeriodsVO().createRow();
            Calendar cal = Calendar.getInstance();
            String pattern = "MMM-yyyy";
            SimpleDateFormat sdf = new SimpleDateFormat(pattern);
            
            cal.setTime(getStartDate());
            cal.add(Calendar.MONTH, i);
            r.setAttribute("StartDate", new Timestamp(cal.getTimeInMillis()));
            r.setAttribute("PeriodName", sdf.format(cal.getTimeInMillis()));
            r.setAttribute("PeriodNo", periodno);
            
            if (i<=2) {
                r.setAttribute("QuarterNo", 1);
            }
            else if (i<=5) {
                r.setAttribute("QuarterNo", 2);
            }

            else if (i<=8) {
                r.setAttribute("QuarterNo", 3);
            }
            else {
                r.setAttribute("QuarterNo", 4);
            }
            cal.setTime((Timestamp)r.getAttribute("StartDate"));
            cal.add(Calendar.MONTH, 1);
            cal.add(Calendar.DATE, -1);
            r.setAttribute("EndDate", new Timestamp(cal.getTimeInMillis()));
            
            getGlPeriodsVO().insertRow(r);
            
            if (i==2 || i==5|| i==8 || i==11) {
               periodno=periodno+1;
                Row adj=getGlPeriodsVO().createRow();
                adj.setAttribute("StartDate", r.getAttribute("StartDate"));
               adj.setAttribute("EndDate", r.getAttribute("EndDate"));
               adj.setAttribute("QuarterNo", r.getAttribute("QuarterNo"));
               adj.setAttribute("PeriodNo",periodno );
               adj.setAttribute("PeriodName", "ADJ-"+r.getAttribute("PeriodName"));
                   
                adj.setAttribute("IsAdjustment", "Y");
               getGlPeriodsVO().insertRow(adj);    
               
           }
            periodno=periodno+1;
            
        }
        getDBTransaction().commit();
        getDBTransaction().getRootApplicationModule().findViewObject("GlPeriodsDetCRUD").executeQuery();
    }
}

