package erpfms.modelfms.fmsvo;

import erpfms.modelfms.fmseo.GlVoucherHeaderImpl;

import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import erpglobals.modelglobals.ERPViewRowImpl;

import java.math.BigDecimal;

import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 17 22:11:00 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlVoucherHeaderVORowImpl extends ERPViewRowImpl {


    public static final int ENTITY_GLVOUCHERHEADER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        VoucherHeaderSno,
        VoucherTypeId,
        VoucherHeaderCode,
        VoucherDate,
        Remarks,
        BatchId,
        CreatedBy,
        LastUpdatedBy,
        SupervisedBy,
        SupervisedDate,
        IsSupervised,
        CompanyId,
        CurrencySno,
        ExchangeRate,
        TempProjectId,
        FileName,
        ReversedBy,
        ReversedDate,
        ReversedVoucherId,
        UnSupervisedBy,
        UnSupervisedDate,
        SourceDocumentSno,
        CreatedDate,
        LastUpdatedDate,
        PeriodSno,
        PeriodStartDate,
        PeriodEndDate,
        FiscalYearSno,
        SourceDocumentType,
        TempDepartmentId,
        LocationId,
        ReferenceNo,
        GlobalCompanyId,
        txtLocationName,
        txtVoucherTypeName,
        txtPeriodName,
        txtProjectName,
        txtTempDepartmentName,
        VoucherCategorySno,
        txtSumDebit,
        txtSumCredit,
        IsUnsupervised,
        YearDigit,
        MonthDigit,
        VoucherNoPrefix,
        IsReversed,
        ReversePeriodSno,
        ReversePeriodDate,
        ReverseFiscalYearSno,
        ReversePeriodStartDate,
        ReversePeriodEndDate,
        ReverseReason,
        txtReverseVoucherCode,
        ReversedVoucherCode,
        GlInstallmentKnockoffVO,
        GlVoucherAccountsVO,
        AdminCompanyVO,
        GlPeriodsVO,
        GlProjectsVO,
        GlVoucherLinesVO,
        AdminCompanyVO1,
        GlVoucherTypesVO,
        AccGlVoucherTypesVO,
        AccGlPeriodsVO,
        AccAdminCompanyVO,
        AccGlBatchSetupVO,
        AccGlProjectsVO,
        GlAccountGroupVO1,
        AccAdminCompanyForCompVO,
        AccSysSystemParameterVO,
        AccAdminDepartCompanyVO,
        AccGlParameterVouchGenVO,
        AccGlCoaUserCompanyVO,
        AccSysUserVoucherTypeAccess,
        AccSysGeneralValueVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int VOUCHERHEADERSNO = AttributesEnum.VoucherHeaderSno.index();
    public static final int VOUCHERTYPEID = AttributesEnum.VoucherTypeId.index();
    public static final int VOUCHERHEADERCODE = AttributesEnum.VoucherHeaderCode.index();
    public static final int VOUCHERDATE = AttributesEnum.VoucherDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int BATCHID = AttributesEnum.BatchId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int CURRENCYSNO = AttributesEnum.CurrencySno.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int TEMPPROJECTID = AttributesEnum.TempProjectId.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int REVERSEDBY = AttributesEnum.ReversedBy.index();
    public static final int REVERSEDDATE = AttributesEnum.ReversedDate.index();
    public static final int REVERSEDVOUCHERID = AttributesEnum.ReversedVoucherId.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int SOURCEDOCUMENTSNO = AttributesEnum.SourceDocumentSno.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int PERIODSNO = AttributesEnum.PeriodSno.index();
    public static final int PERIODSTARTDATE = AttributesEnum.PeriodStartDate.index();
    public static final int PERIODENDDATE = AttributesEnum.PeriodEndDate.index();
    public static final int FISCALYEARSNO = AttributesEnum.FiscalYearSno.index();
    public static final int SOURCEDOCUMENTTYPE = AttributesEnum.SourceDocumentType.index();
    public static final int TEMPDEPARTMENTID = AttributesEnum.TempDepartmentId.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int REFERENCENO = AttributesEnum.ReferenceNo.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTVOUCHERTYPENAME = AttributesEnum.txtVoucherTypeName.index();
    public static final int TXTPERIODNAME = AttributesEnum.txtPeriodName.index();
    public static final int TXTPROJECTNAME = AttributesEnum.txtProjectName.index();
    public static final int TXTTEMPDEPARTMENTNAME = AttributesEnum.txtTempDepartmentName.index();
    public static final int VOUCHERCATEGORYSNO = AttributesEnum.VoucherCategorySno.index();
    public static final int TXTSUMDEBIT = AttributesEnum.txtSumDebit.index();
    public static final int TXTSUMCREDIT = AttributesEnum.txtSumCredit.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int YEARDIGIT = AttributesEnum.YearDigit.index();
    public static final int MONTHDIGIT = AttributesEnum.MonthDigit.index();
    public static final int VOUCHERNOPREFIX = AttributesEnum.VoucherNoPrefix.index();
    public static final int ISREVERSED = AttributesEnum.IsReversed.index();
    public static final int REVERSEPERIODSNO = AttributesEnum.ReversePeriodSno.index();
    public static final int REVERSEPERIODDATE = AttributesEnum.ReversePeriodDate.index();
    public static final int REVERSEFISCALYEARSNO = AttributesEnum.ReverseFiscalYearSno.index();
    public static final int REVERSEPERIODSTARTDATE = AttributesEnum.ReversePeriodStartDate.index();
    public static final int REVERSEPERIODENDDATE = AttributesEnum.ReversePeriodEndDate.index();
    public static final int REVERSEREASON = AttributesEnum.ReverseReason.index();
    public static final int TXTREVERSEVOUCHERCODE = AttributesEnum.txtReverseVoucherCode.index();
    public static final int REVERSEDVOUCHERCODE = AttributesEnum.ReversedVoucherCode.index();
    public static final int GLINSTALLMENTKNOCKOFFVO = AttributesEnum.GlInstallmentKnockoffVO.index();
    public static final int GLVOUCHERACCOUNTSVO = AttributesEnum.GlVoucherAccountsVO.index();
    public static final int ADMINCOMPANYVO = AttributesEnum.AdminCompanyVO.index();
    public static final int GLPERIODSVO = AttributesEnum.GlPeriodsVO.index();
    public static final int GLPROJECTSVO = AttributesEnum.GlProjectsVO.index();
    public static final int GLVOUCHERLINESVO = AttributesEnum.GlVoucherLinesVO.index();
    public static final int ADMINCOMPANYVO1 = AttributesEnum.AdminCompanyVO1.index();
    public static final int GLVOUCHERTYPESVO = AttributesEnum.GlVoucherTypesVO.index();
    public static final int ACCGLVOUCHERTYPESVO = AttributesEnum.AccGlVoucherTypesVO.index();
    public static final int ACCGLPERIODSVO = AttributesEnum.AccGlPeriodsVO.index();
    public static final int ACCADMINCOMPANYVO = AttributesEnum.AccAdminCompanyVO.index();
    public static final int ACCGLBATCHSETUPVO = AttributesEnum.AccGlBatchSetupVO.index();
    public static final int ACCGLPROJECTSVO = AttributesEnum.AccGlProjectsVO.index();
    public static final int GLACCOUNTGROUPVO1 = AttributesEnum.GlAccountGroupVO1.index();
    public static final int ACCADMINCOMPANYFORCOMPVO = AttributesEnum.AccAdminCompanyForCompVO.index();
    public static final int ACCSYSSYSTEMPARAMETERVO = AttributesEnum.AccSysSystemParameterVO.index();
    public static final int ACCADMINDEPARTCOMPANYVO = AttributesEnum.AccAdminDepartCompanyVO.index();
    public static final int ACCGLPARAMETERVOUCHGENVO = AttributesEnum.AccGlParameterVouchGenVO.index();
    public static final int ACCGLCOAUSERCOMPANYVO = AttributesEnum.AccGlCoaUserCompanyVO.index();
    public static final int ACCSYSUSERVOUCHERTYPEACCESS = AttributesEnum.AccSysUserVoucherTypeAccess.index();
    public static final int ACCSYSGENERALVALUEVO = AttributesEnum.AccSysGeneralValueVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlVoucherHeaderVORowImpl() {
    }

    /**
     * Gets GlVoucherHeader entity object.
     * @return the GlVoucherHeader
     */
    public GlVoucherHeaderImpl getGlVoucherHeader() {
        return (GlVoucherHeaderImpl) getEntity(ENTITY_GLVOUCHERHEADER);
    }

    /**
     * Gets the attribute value for VOUCHER_HEADER_SNO using the alias name VoucherHeaderSno.
     * @return the VOUCHER_HEADER_SNO
     */
    public Integer getVoucherHeaderSno() {
        return (Integer) getAttributeInternal(VOUCHERHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_HEADER_SNO using the alias name VoucherHeaderSno.
     * @param value value to set the VOUCHER_HEADER_SNO
     */
    public void setVoucherHeaderSno(Integer value) {
        setAttributeInternal(VOUCHERHEADERSNO, value);
    }

    /**
     * Gets the attribute value for VOUCHER_TYPE_ID using the alias name VoucherTypeId.
     * @return the VOUCHER_TYPE_ID
     */
    public Integer getVoucherTypeId() {
        return (Integer) getAttributeInternal(VOUCHERTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_TYPE_ID using the alias name VoucherTypeId.
     * @param value value to set the VOUCHER_TYPE_ID
     */
    public void setVoucherTypeId(Integer value) {
        setAttributeInternal(VOUCHERTYPEID, value);
    }

    /**
     * Gets the attribute value for VOUCHER_HEADER_CODE using the alias name VoucherHeaderCode.
     * @return the VOUCHER_HEADER_CODE
     */
    public Long getVoucherHeaderCode() {
        return (Long) getAttributeInternal(VOUCHERHEADERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_HEADER_CODE using the alias name VoucherHeaderCode.
     * @param value value to set the VOUCHER_HEADER_CODE
     */
    public void setVoucherHeaderCode(Long value) {
        setAttributeInternal(VOUCHERHEADERCODE, value);
    }

    /**
     * Gets the attribute value for VOUCHER_DATE using the alias name VoucherDate.
     * @return the VOUCHER_DATE
     */
    public Timestamp getVoucherDate() {
        return (Timestamp) getAttributeInternal(VOUCHERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_DATE using the alias name VoucherDate.
     * @param value value to set the VOUCHER_DATE
     */
    public void setVoucherDate(Timestamp value) {
        setAttributeInternal(VOUCHERDATE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for BATCH_ID using the alias name BatchId.
     * @return the BATCH_ID
     */
    public Integer getBatchId() {
        return (Integer) getAttributeInternal(BATCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCH_ID using the alias name BatchId.
     * @param value value to set the BATCH_ID
     */
    public void setBatchId(Integer value) {
        setAttributeInternal(BATCHID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @return the SUPERVISED_BY
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @param value value to set the SUPERVISED_BY
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @return the SUPERVISED_DATE
     */
    public Timestamp getSupervisedDate() {
        return (Timestamp) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @param value value to set the SUPERVISED_DATE
     */
    public void setSupervisedDate(Timestamp value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @return the IS_SUPERVISED
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @param value value to set the IS_SUPERVISED
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID using the alias name CompanyId.
     * @return the COMPANY_ID
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID using the alias name CompanyId.
     * @param value value to set the COMPANY_ID
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
        getAccGlPeriodsVO().setNamedWhereClauseParam("P_ADF_COMPANY_ID", value == null ? -1 : value);
        getAccGlPeriodsVO().executeQuery();
        getAccGlProjectsVO().setNamedWhereClauseParam("P_ADF_COMPANY_ID", value == null ? -1 : value);
        getAccGlProjectsVO().executeQuery();
        getAccSysUserVoucherTypeAccess().setNamedWhereClauseParam("P_ADF_COMPANY_ID", value == null ? -1 : value);
        getAccSysUserVoucherTypeAccess().setNamedWhereClauseParam("P_ADF_USER_ID", ERPGlobalPLSQLClass.doGetModelUserSno());
        getAccSysUserVoucherTypeAccess().executeQuery();
        getAccGlBatchSetupVO().setNamedWhereClauseParam("P_ADF_COMPANY_ID", value == null ? -1 : value);
        getAccGlBatchSetupVO().executeQuery();
        getAccAdminDepartCompanyVO().setNamedWhereClauseParam("P_ADF_COMP_CODE", value == null ? -1 : value);
        getAccAdminDepartCompanyVO().setNamedWhereClauseParam("P_ADF_USER_ID", ERPGlobalPLSQLClass.doGetModelUserSno());
        getAccAdminDepartCompanyVO().executeQuery();

    }

    /**
     * Gets the attribute value for CURRENCY_SNO using the alias name CurrencySno.
     * @return the CURRENCY_SNO
     */
    public Integer getCurrencySno() {
        return (Integer) getAttributeInternal(CURRENCYSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_SNO using the alias name CurrencySno.
     * @param value value to set the CURRENCY_SNO
     */
    public void setCurrencySno(Integer value) {
        setAttributeInternal(CURRENCYSNO, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for TEMP_PROJECT_ID using the alias name TempProjectId.
     * @return the TEMP_PROJECT_ID
     */
    public Integer getTempProjectId() {
        return (Integer) getAttributeInternal(TEMPPROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TEMP_PROJECT_ID using the alias name TempProjectId.
     * @param value value to set the TEMP_PROJECT_ID
     */
    public void setTempProjectId(Integer value) {
        setAttributeInternal(TEMPPROJECTID, value);
        RowIterator glVoucherLinesVO = getGlVoucherLinesVO();
        
        while (glVoucherLinesVO.hasNext()) {
            System.out.println(" i am looping");
           glVoucherLinesVO.next().setAttribute("ProjectSno", value);
        } 
        getDBTransaction().getRootApplicationModule().findViewObject("GlVoucherLinesDETCRUD").executeQuery();
         
    }

    /**
     * Gets the attribute value for FILE_NAME using the alias name FileName.
     * @return the FILE_NAME
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName.
     * @param value value to set the FILE_NAME
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for REVERSED_BY using the alias name ReversedBy.
     * @return the REVERSED_BY
     */
    public Integer getReversedBy() {
        return (Integer) getAttributeInternal(REVERSEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSED_BY using the alias name ReversedBy.
     * @param value value to set the REVERSED_BY
     */
    public void setReversedBy(Integer value) {
        setAttributeInternal(REVERSEDBY, value);
    }

    /**
     * Gets the attribute value for REVERSED_DATE using the alias name ReversedDate.
     * @return the REVERSED_DATE
     */
    public Timestamp getReversedDate() {
        return (Timestamp) getAttributeInternal(REVERSEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSED_DATE using the alias name ReversedDate.
     * @param value value to set the REVERSED_DATE
     */
    public void setReversedDate(Timestamp value) {
        setAttributeInternal(REVERSEDDATE, value);
    }

    /**
     * Gets the attribute value for REVERSED_VOUCHER_ID using the alias name ReversedVoucherId.
     * @return the REVERSED_VOUCHER_ID
     */
    public Integer getReversedVoucherId() {
        return (Integer) getAttributeInternal(REVERSEDVOUCHERID);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSED_VOUCHER_ID using the alias name ReversedVoucherId.
     * @param value value to set the REVERSED_VOUCHER_ID
     */
    public void setReversedVoucherId(Integer value) {
        setAttributeInternal(REVERSEDVOUCHERID, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @return the UN_SUPERVISED_BY
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @param value value to set the UN_SUPERVISED_BY
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @return the UN_SUPERVISED_DATE
     */
    public Timestamp getUnSupervisedDate() {
        return (Timestamp) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @param value value to set the UN_SUPERVISED_DATE
     */
    public void setUnSupervisedDate(Timestamp value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for SOURCE_DOCUMENT_SNO using the alias name SourceDocumentSno.
     * @return the SOURCE_DOCUMENT_SNO
     */
    public Integer getSourceDocumentSno() {
        return (Integer) getAttributeInternal(SOURCEDOCUMENTSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_DOCUMENT_SNO using the alias name SourceDocumentSno.
     * @param value value to set the SOURCE_DOCUMENT_SNO
     */
    public void setSourceDocumentSno(Integer value) {
        setAttributeInternal(SOURCEDOCUMENTSNO, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }


    /**
     * Gets the attribute value for PERIOD_SNO using the alias name PeriodSno.
     * @return the PERIOD_SNO
     */
    public Integer getPeriodSno() {
        return (Integer) getAttributeInternal(PERIODSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIOD_SNO using the alias name PeriodSno.
     * @param value value to set the PERIOD_SNO
     */
    public void setPeriodSno(Integer value) {
        setAttributeInternal(PERIODSNO, value);
    }

    /**
     * Gets the attribute value for PERIOD_START_DATE using the alias name PeriodStartDate.
     * @return the PERIOD_START_DATE
     */
    public Timestamp getPeriodStartDate() {
        return (Timestamp) getAttributeInternal(PERIODSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIOD_START_DATE using the alias name PeriodStartDate.
     * @param value value to set the PERIOD_START_DATE
     */
    public void setPeriodStartDate(Timestamp value) {
        setAttributeInternal(PERIODSTARTDATE, value);
    }

    /**
     * Gets the attribute value for PERIOD_END_DATE using the alias name PeriodEndDate.
     * @return the PERIOD_END_DATE
     */
    public Timestamp getPeriodEndDate() {
        return (Timestamp) getAttributeInternal(PERIODENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIOD_END_DATE using the alias name PeriodEndDate.
     * @param value value to set the PERIOD_END_DATE
     */
    public void setPeriodEndDate(Timestamp value) {
        setAttributeInternal(PERIODENDDATE, value);
    }

    /**
     * Gets the attribute value for FISCAL_YEAR_SNO using the alias name FiscalYearSno.
     * @return the FISCAL_YEAR_SNO
     */
    public Integer getFiscalYearSno() {
        return (Integer) getAttributeInternal(FISCALYEARSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for FISCAL_YEAR_SNO using the alias name FiscalYearSno.
     * @param value value to set the FISCAL_YEAR_SNO
     */
    public void setFiscalYearSno(Integer value) {
        setAttributeInternal(FISCALYEARSNO, value);
    }

    /**
     * Gets the attribute value for SOURCE_DOCUMENT_TYPE using the alias name SourceDocumentType.
     * @return the SOURCE_DOCUMENT_TYPE
     */
    public Integer getSourceDocumentType() {
        return (Integer) getAttributeInternal(SOURCEDOCUMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_DOCUMENT_TYPE using the alias name SourceDocumentType.
     * @param value value to set the SOURCE_DOCUMENT_TYPE
     */
    public void setSourceDocumentType(Integer value) {
        setAttributeInternal(SOURCEDOCUMENTTYPE, value);
    }

    /**
     * Gets the attribute value for TEMP_DEPARTMENT_ID using the alias name TempDepartmentId.
     * @return the TEMP_DEPARTMENT_ID
     */
    public Integer getTempDepartmentId() {
        return (Integer) getAttributeInternal(TEMPDEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TEMP_DEPARTMENT_ID using the alias name TempDepartmentId.
     * @param value value to set the TEMP_DEPARTMENT_ID
     */
    public void setTempDepartmentId(Integer value) {
        setAttributeInternal(TEMPDEPARTMENTID, value);
       
        RowIterator glVoucherLinesVO = getGlVoucherLinesVO();
        
        while (glVoucherLinesVO.hasNext()) {
            System.out.println(" i am looping");
           glVoucherLinesVO.next().setAttribute("DepartmentId", value);
        } 
        getDBTransaction().getRootApplicationModule().findViewObject("GlVoucherLinesDETCRUD").executeQuery();
    }

    /**
     * Gets the attribute value for LOCATION_ID using the alias name LocationId.
     * @return the LOCATION_ID
     */
    public BigDecimal getLocationId() {
        return (BigDecimal) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LocationId.
     * @param value value to set the LOCATION_ID
     */
    public void setLocationId(BigDecimal value) {
        setAttributeInternal(LOCATIONID, value);
        setCompanyId(doGetCompanyIDByLocation(value.intValue(), getGlobalCompanyId()));
        /*here we are getting the company type level so that we can store the company if accodringly in company id field*/
        
        /*
        Integer erpCompanyId=-1;
       
        
        //getting company type
        getAccSysSystemParameterVO().setNamedWhereClauseParam("P_ADF_GLOBAL_COMPANY_ID", getGlobalCompanyId());
        getAccSysSystemParameterVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "COMPANY_TYPE_SNO");
        getAccSysSystemParameterVO().executeQuery();
        Integer erpCompanyType=Integer.parseInt(getAccSysSystemParameterVO().first().getAttribute("ParameterValue").toString()) ;
        getAccAdminCompanyForCompVO().setNamedWhereClauseParam("P_ADF_COMP_CODE",value==null?-1:value.intValue());
        getAccAdminCompanyForCompVO().executeQuery();
        while(true && getAccAdminCompanyForCompVO().getRowCount()>0) {
            //assigning companyid to company685
            //
            Integer ccode= Integer.parseInt( getAccAdminCompanyForCompVO().first().getAttribute("ParentCompCode").toString() );
            getAccAdminCompanyForCompVO().setNamedWhereClauseParam("P_ADF_COMP_CODE", ccode);
            getAccAdminCompanyForCompVO().executeQuery();
            if (Integer.parseInt( getAccAdminCompanyForCompVO().first().getAttribute("CompanyTypeSno").toString())== erpCompanyType) {
                //setCompanyId(Integer.parseInt( getAccAdminCompanyForCompVO().first().getAttribute("CompCode").toString()));
             erpCompanyId=  Integer.parseInt( getAccAdminCompanyForCompVO().first().getAttribute("CompCode").toString()); 
               break;
           }
        }
        setCompanyId(erpCompanyId);
        */
        //System.out.println(getCompanyId() + " getcompanyid");
         
        
        
    }

    /**
     * Gets the attribute value for REFERENCE_NO using the alias name ReferenceNo.
     * @return the REFERENCE_NO
     */
    public String getReferenceNo() {
        return (String) getAttributeInternal(REFERENCENO);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_NO using the alias name ReferenceNo.
     * @param value value to set the REFERENCE_NO
     */
    public void setReferenceNo(String value) {
        setAttributeInternal(REFERENCENO, value);
    }

    /**
     * Gets the attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @return the GLOBAL_COMPANY_ID
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @param value value to set the GLOBAL_COMPANY_ID
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for txt_Location_Name using the alias name txtLocationName.
     * @return the txt_Location_Name
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Location_Name using the alias name txtLocationName.
     * @param value value to set the txt_Location_Name
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for TXT_VOUCHER_TYPE_NAME using the alias name txtVoucherTypeName.
     * @return the TXT_VOUCHER_TYPE_NAME
     */
    public String gettxtVoucherTypeName() {
        return (String) getAttributeInternal(TXTVOUCHERTYPENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_VOUCHER_TYPE_NAME using the alias name txtVoucherTypeName.
     * @param value value to set the TXT_VOUCHER_TYPE_NAME
     */
    public void settxtVoucherTypeName(String value) {
        setAttributeInternal(TXTVOUCHERTYPENAME, value);
    }

    /**
     * Gets the attribute value for TXT_PERIOD_NAME using the alias name txtPeriodName.
     * @return the TXT_PERIOD_NAME
     */
    public String gettxtPeriodName() {
        return (String) getAttributeInternal(TXTPERIODNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PERIOD_NAME using the alias name txtPeriodName.
     * @param value value to set the TXT_PERIOD_NAME
     */
    public void settxtPeriodName(String value) {
        setAttributeInternal(TXTPERIODNAME, value);
    }

    /**
     * Gets the attribute value for TXT_PROJECT_NAME using the alias name txtProjectName.
     * @return the TXT_PROJECT_NAME
     */
    public String gettxtProjectName() {
        return (String) getAttributeInternal(TXTPROJECTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PROJECT_NAME using the alias name txtProjectName.
     * @param value value to set the TXT_PROJECT_NAME
     */
    public void settxtProjectName(String value) {
        setAttributeInternal(TXTPROJECTNAME, value);
    }

    /**
     * Gets the attribute value for txt_Temp_Department_Name using the alias name txtTempDepartmentName.
     * @return the txt_Temp_Department_Name
     */
    public String gettxtTempDepartmentName() {
        return (String) getAttributeInternal(TXTTEMPDEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Temp_Department_Name using the alias name txtTempDepartmentName.
     * @param value value to set the txt_Temp_Department_Name
     */
    public void settxtTempDepartmentName(String value) {
        setAttributeInternal(TXTTEMPDEPARTMENTNAME, value);
        
    }

    /**
     * Gets the attribute value for VOUCHER_CATEGORY_SNO using the alias name VoucherCategorySno.
     * @return the VOUCHER_CATEGORY_SNO
     */
    public Integer getVoucherCategorySno() {
        return (Integer) getAttributeInternal(VOUCHERCATEGORYSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_CATEGORY_SNO using the alias name VoucherCategorySno.
     * @param value value to set the VOUCHER_CATEGORY_SNO
     */
    public void setVoucherCategorySno(Integer value) {
        setAttributeInternal(VOUCHERCATEGORYSNO, value);
    }

    /**
     * Gets the attribute value for txt_Sum_Debit using the alias name txtSumDebit.
     * @return the txt_Sum_Debit
     */
    public BigDecimal gettxtSumDebit() {
        return (BigDecimal) getAttributeInternal(TXTSUMDEBIT);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Sum_Debit using the alias name txtSumDebit.
     * @param value value to set the txt_Sum_Debit
     */
    public void settxtSumDebit(BigDecimal value) {
        setAttributeInternal(TXTSUMDEBIT, value);
    }

    /**
     * Gets the attribute value for txt_Sum_Credit using the alias name txtSumCredit.
     * @return the txt_Sum_Credit
     */
    public BigDecimal gettxtSumCredit() {
        return (BigDecimal) getAttributeInternal(TXTSUMCREDIT);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Sum_Credit using the alias name txtSumCredit.
     * @param value value to set the txt_Sum_Credit
     */
    public void settxtSumCredit(BigDecimal value) {
        setAttributeInternal(TXTSUMCREDIT, value);
    }

    /**
     * Gets the attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @return the IS_UNSUPERVISED
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @param value value to set the IS_UNSUPERVISED
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for YEAR_DIGIT using the alias name YearDigit.
     * @return the YEAR_DIGIT
     */
    public Integer getYearDigit() {
        return (Integer) getAttributeInternal(YEARDIGIT);
    }

    /**
     * Sets <code>value</code> as attribute value for YEAR_DIGIT using the alias name YearDigit.
     * @param value value to set the YEAR_DIGIT
     */
    public void setYearDigit(Integer value) {
        setAttributeInternal(YEARDIGIT, value);
    }

    /**
     * Gets the attribute value for MONTH_DIGIT using the alias name MonthDigit.
     * @return the MONTH_DIGIT
     */
    public String getMonthDigit() {
        return (String) getAttributeInternal(MONTHDIGIT);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH_DIGIT using the alias name MonthDigit.
     * @param value value to set the MONTH_DIGIT
     */
    public void setMonthDigit(String value) {
        setAttributeInternal(MONTHDIGIT, value);
    }

    /**
     * Gets the attribute value for VOUCHER_NO_PREFIX using the alias name VoucherNoPrefix.
     * @return the VOUCHER_NO_PREFIX
     */
    public Integer getVoucherNoPrefix() {
        return (Integer) getAttributeInternal(VOUCHERNOPREFIX);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_NO_PREFIX using the alias name VoucherNoPrefix.
     * @param value value to set the VOUCHER_NO_PREFIX
     */
    public void setVoucherNoPrefix(Integer value) {
        setAttributeInternal(VOUCHERNOPREFIX, value);
    }

    /**
     * Gets the attribute value for IS_REVERSED using the alias name IsReversed.
     * @return the IS_REVERSED
     */
    public String getIsReversed() {
        return (String) getAttributeInternal(ISREVERSED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_REVERSED using the alias name IsReversed.
     * @param value value to set the IS_REVERSED
     */
    public void setIsReversed(String value) {
        setAttributeInternal(ISREVERSED, value);
    }

    /**
     * Gets the attribute value for REVERSE_PERIOD_SNO using the alias name ReversePeriodSno.
     * @return the REVERSE_PERIOD_SNO
     */
    public Integer getReversePeriodSno() {
        return (Integer) getAttributeInternal(REVERSEPERIODSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSE_PERIOD_SNO using the alias name ReversePeriodSno.
     * @param value value to set the REVERSE_PERIOD_SNO
     */
    public void setReversePeriodSno(Integer value) {
        setAttributeInternal(REVERSEPERIODSNO, value);
    }

    /**
     * Gets the attribute value for REVERSE_PERIOD_DATE using the alias name ReversePeriodDate.
     * @return the REVERSE_PERIOD_DATE
     */
    public Timestamp getReversePeriodDate() {
        return (Timestamp) getAttributeInternal(REVERSEPERIODDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSE_PERIOD_DATE using the alias name ReversePeriodDate.
     * @param value value to set the REVERSE_PERIOD_DATE
     */
    public void setReversePeriodDate(Timestamp value) {
        setAttributeInternal(REVERSEPERIODDATE, value);
    }

    /**
     * Gets the attribute value for REVERSE_FISCAL_YEAR_SNO using the alias name ReverseFiscalYearSno.
     * @return the REVERSE_FISCAL_YEAR_SNO
     */
    public Integer getReverseFiscalYearSno() {
        return (Integer) getAttributeInternal(REVERSEFISCALYEARSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSE_FISCAL_YEAR_SNO using the alias name ReverseFiscalYearSno.
     * @param value value to set the REVERSE_FISCAL_YEAR_SNO
     */
    public void setReverseFiscalYearSno(Integer value) {
        setAttributeInternal(REVERSEFISCALYEARSNO, value);
    }

    /**
     * Gets the attribute value for REVERSE_PERIOD_START_DATE using the alias name ReversePeriodStartDate.
     * @return the REVERSE_PERIOD_START_DATE
     */
    public Timestamp getReversePeriodStartDate() {
        return (Timestamp) getAttributeInternal(REVERSEPERIODSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSE_PERIOD_START_DATE using the alias name ReversePeriodStartDate.
     * @param value value to set the REVERSE_PERIOD_START_DATE
     */
    public void setReversePeriodStartDate(Timestamp value) {
        setAttributeInternal(REVERSEPERIODSTARTDATE, value);
    }

    /**
     * Gets the attribute value for REVERSE_PERIOD_END_DATE using the alias name ReversePeriodEndDate.
     * @return the REVERSE_PERIOD_END_DATE
     */
    public Timestamp getReversePeriodEndDate() {
        return (Timestamp) getAttributeInternal(REVERSEPERIODENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSE_PERIOD_END_DATE using the alias name ReversePeriodEndDate.
     * @param value value to set the REVERSE_PERIOD_END_DATE
     */
    public void setReversePeriodEndDate(Timestamp value) {
        setAttributeInternal(REVERSEPERIODENDDATE, value);
    }

    /**
     * Gets the attribute value for REVERSE_REASON using the alias name ReverseReason.
     * @return the REVERSE_REASON
     */
    public String getReverseReason() {
        return (String) getAttributeInternal(REVERSEREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSE_REASON using the alias name ReverseReason.
     * @param value value to set the REVERSE_REASON
     */
    public void setReverseReason(String value) {
        setAttributeInternal(REVERSEREASON, value);
    }


    /**
     * Gets the attribute value for txt_Reverse_Voucher_Code using the alias name txtReverseVoucherCode.
     * @return the txt_Reverse_Voucher_Code
     */
    public Long gettxtReverseVoucherCode() {
        return (Long) getAttributeInternal(TXTREVERSEVOUCHERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Reverse_Voucher_Code using the alias name txtReverseVoucherCode.
     * @param value value to set the txt_Reverse_Voucher_Code
     */
    public void settxtReverseVoucherCode(Long value) {
        setAttributeInternal(TXTREVERSEVOUCHERCODE, value);
    }

    /**
     * Gets the attribute value for REVERSED_VOUCHER_CODE using the alias name ReversedVoucherCode.
     * @return the REVERSED_VOUCHER_CODE
     */
    public Long getReversedVoucherCode() {
        return (Long) getAttributeInternal(REVERSEDVOUCHERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSED_VOUCHER_CODE using the alias name ReversedVoucherCode.
     * @param value value to set the REVERSED_VOUCHER_CODE
     */
    public void setReversedVoucherCode(Long value) {
        setAttributeInternal(REVERSEDVOUCHERCODE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GlInstallmentKnockoffVO.
     */
    public RowIterator getGlInstallmentKnockoffVO() {
        return (RowIterator) getAttributeInternal(GLINSTALLMENTKNOCKOFFVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GlVoucherAccountsVO.
     */
    public RowIterator getGlVoucherAccountsVO() {
        return (RowIterator) getAttributeInternal(GLVOUCHERACCOUNTSVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyVO.
     */
    public Row getAdminCompanyVO() {
        return (Row) getAttributeInternal(ADMINCOMPANYVO);
    }

    /**
     * Sets the master-detail link AdminCompanyVO between this object and <code>value</code>.
     */
    public void setAdminCompanyVO(Row value) {
        setAttributeInternal(ADMINCOMPANYVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlPeriodsVO.
     */
    public Row getGlPeriodsVO() {
        return (Row) getAttributeInternal(GLPERIODSVO);
    }

    /**
     * Sets the master-detail link GlPeriodsVO between this object and <code>value</code>.
     */
    public void setGlPeriodsVO(Row value) {
        setAttributeInternal(GLPERIODSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlProjectsVO.
     */
    public Row getGlProjectsVO() {
        return (Row) getAttributeInternal(GLPROJECTSVO);
    }

    /**
     * Sets the master-detail link GlProjectsVO between this object and <code>value</code>.
     */
    public void setGlProjectsVO(Row value) {
        setAttributeInternal(GLPROJECTSVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GlVoucherLinesVO.
     */
    public RowIterator getGlVoucherLinesVO() {
        return (RowIterator) getAttributeInternal(GLVOUCHERLINESVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyVO1.
     */
    public Row getAdminCompanyVO1() {
        return (Row) getAttributeInternal(ADMINCOMPANYVO1);
    }

    /**
     * Sets the master-detail link AdminCompanyVO1 between this object and <code>value</code>.
     */
    public void setAdminCompanyVO1(Row value) {
        setAttributeInternal(ADMINCOMPANYVO1, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlVoucherTypesVO.
     */
    public Row getGlVoucherTypesVO() {
        return (Row) getAttributeInternal(GLVOUCHERTYPESVO);
    }

    /**
     * Sets the master-detail link GlVoucherTypesVO between this object and <code>value</code>.
     */
    public void setGlVoucherTypesVO(Row value) {
        setAttributeInternal(GLVOUCHERTYPESVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlVoucherTypesVO.
     */
    public RowSet getAccGlVoucherTypesVO() {
        RowSet rs=(RowSet)getAttributeInternal(ACCGLVOUCHERTYPESVO);
        rs.setNamedWhereClauseParam("P_ADF_COMPANY_ID", getCompanyId()==null?-1:getCompanyId());
        rs.executeQuery();
        return rs;
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlPeriodsVO.
     */
    public RowSet getAccGlPeriodsVO() {
        return (RowSet) getAttributeInternal(ACCGLPERIODSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyVO.
     */
    public RowSet getAccAdminCompanyVO() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlBatchSetupVO.
     */
    public RowSet getAccGlBatchSetupVO() {
        return (RowSet) getAttributeInternal(ACCGLBATCHSETUPVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlProjectsVO.
     */
    public RowSet getAccGlProjectsVO() {
        return (RowSet)getAttributeInternal(ACCGLPROJECTSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GlAccountGroupVO1.
     */
    public RowSet getGlAccountGroupVO1() {
        return (RowSet) getAttributeInternal(GLACCOUNTGROUPVO1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyForCompVO.
     */
    public RowSet getAccAdminCompanyForCompVO() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYFORCOMPVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysSystemParameterVO.
     */
    public RowSet getAccSysSystemParameterVO() {
        return (RowSet) getAttributeInternal(ACCSYSSYSTEMPARAMETERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminDepartCompanyVO.
     */
    public RowSet getAccAdminDepartCompanyVO() {
        return (RowSet) getAttributeInternal(ACCADMINDEPARTCOMPANYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlParameterVouchGenVO.
     */
    public RowSet getAccGlParameterVouchGenVO() {
        return (RowSet) getAttributeInternal(ACCGLPARAMETERVOUCHGENVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlCoaUserCompanyVO.
     */
    public RowSet getAccGlCoaUserCompanyVO() {
        return (RowSet) getAttributeInternal(ACCGLCOAUSERCOMPANYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysUserVoucherTypeAccess.
     */
    public RowSet getAccSysUserVoucherTypeAccess() {
        RowSet rs=(RowSet)getAttributeInternal(ACCSYSUSERVOUCHERTYPEACCESS);
        rs.setNamedWhereClauseParam("P_ADF_COMPANY_ID", getCompanyId()==null?-1:getCompanyId());
        rs.setNamedWhereClauseParam("P_ADF_USER_ID", ERPGlobalPLSQLClass.doGetModelUserSno());
        rs.executeQuery();
        return rs;
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysGeneralValueVO.
     */
    public RowSet getAccSysGeneralValueVO() {
        return (RowSet) getAttributeInternal(ACCSYSGENERALVALUEVO);
    }

    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method4
        if (getIsSupervised().equals("Y")) {//in case record is supervised
            return false;
       }
        if (getVoucherHeaderSno()>0) {
            
            if (i==TXTPERIODNAME) {
                getAccGlParameterVouchGenVO().setNamedWhereClauseParam("P_ADF_COMPANY_ID", getCompanyId());
                getAccGlParameterVouchGenVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "RESET_VOUCH_ON_PER");
                getAccGlParameterVouchGenVO().executeQuery();
                if (getAccGlParameterVouchGenVO().first().getAttribute("ParameterValue").equals("Y")) {
                    return false;
                }
            }
           if (i==TXTVOUCHERTYPENAME) {
               getAccGlParameterVouchGenVO().setNamedWhereClauseParam("P_ADF_COMPANY_ID", getCompanyId());
               getAccGlParameterVouchGenVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "RESET_VOUCH_ON_VTYPE");
               getAccGlParameterVouchGenVO().executeQuery();
               if (getAccGlParameterVouchGenVO().first().getAttribute("ParameterValue").equals("Y")) {
                   return false;
               }
           }
           if (i==TXTPERIODNAME) {
               getAccGlParameterVouchGenVO().setNamedWhereClauseParam("P_ADF_COMPANY_ID", getCompanyId());
               getAccGlParameterVouchGenVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "RESET_VOUCH_ON_FY");
               getAccGlParameterVouchGenVO().executeQuery();
               if (getAccGlParameterVouchGenVO().first().getAttribute("ParameterValue").equals("Y")) {
                   return false;
               }
           } 
           if (i==TXTLOCATIONNAME) {
               getAccGlParameterVouchGenVO().setNamedWhereClauseParam("P_ADF_COMPANY_ID", getCompanyId());
               getAccGlParameterVouchGenVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "RESET_VOUCH_ON_LOC");
               getAccGlParameterVouchGenVO().executeQuery();
               if (getAccGlParameterVouchGenVO().first().getAttribute("ParameterValue").equals("Y")) {
                   return false;
               }
               //checking  user has miltiple company rights
               getAccGlCoaUserCompanyVO().executeQuery();
               
               if (getAccGlCoaUserCompanyVO().getRowCount()>0) {
                    return false;
               }
               
               
               
           }
            
              
           
       }
        return super.isAttributeUpdateable(i);
    }
}

