package erpfms.modelfms.fmsvo;

import erpfms.modelfms.fmseo.GlVoucherLinesImpl;

import erpglobals.modelglobals.ERPViewRowImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 19 21:34:47 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlVoucherLinesVORowImpl extends ERPViewRowImpl {


    public static final int ENTITY_GLVOUCHERLINES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        VoucherLinesSno,
        VoucherHeaderSno,
        ChartOfAccountId,
        Debit,
        Credit,
        ChequeNo,
        Naration,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        ProjectSno,
        DepartmentId,
        ChequeDate,
        Quantity,
        LastUpdatedDate,
        txtCOADescription,
        txtCOACode,
        txtProjectName,
        txtDepartmentName,
        GlVoucherHeaderVO,
        GlChartOfAccountsVO,
        GlProjectsVO,
        AdminCompanyVO,
        AccGlChartOfAccountsQVO,
        AccGlProjectsVO,
        AccAdminDepartLinCompanyVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int VOUCHERLINESSNO = AttributesEnum.VoucherLinesSno.index();
    public static final int VOUCHERHEADERSNO = AttributesEnum.VoucherHeaderSno.index();
    public static final int CHARTOFACCOUNTID = AttributesEnum.ChartOfAccountId.index();
    public static final int DEBIT = AttributesEnum.Debit.index();
    public static final int CREDIT = AttributesEnum.Credit.index();
    public static final int CHEQUENO = AttributesEnum.ChequeNo.index();
    public static final int NARATION = AttributesEnum.Naration.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PROJECTSNO = AttributesEnum.ProjectSno.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int CHEQUEDATE = AttributesEnum.ChequeDate.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int TXTCOADESCRIPTION = AttributesEnum.txtCOADescription.index();
    public static final int TXTCOACODE = AttributesEnum.txtCOACode.index();
    public static final int TXTPROJECTNAME = AttributesEnum.txtProjectName.index();
    public static final int TXTDEPARTMENTNAME = AttributesEnum.txtDepartmentName.index();
    public static final int GLVOUCHERHEADERVO = AttributesEnum.GlVoucherHeaderVO.index();
    public static final int GLCHARTOFACCOUNTSVO = AttributesEnum.GlChartOfAccountsVO.index();
    public static final int GLPROJECTSVO = AttributesEnum.GlProjectsVO.index();
    public static final int ADMINCOMPANYVO = AttributesEnum.AdminCompanyVO.index();
    public static final int ACCGLCHARTOFACCOUNTSQVO = AttributesEnum.AccGlChartOfAccountsQVO.index();
    public static final int ACCGLPROJECTSVO = AttributesEnum.AccGlProjectsVO.index();
    public static final int ACCADMINDEPARTLINCOMPANYVO = AttributesEnum.AccAdminDepartLinCompanyVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlVoucherLinesVORowImpl() {
    }

    /**
     * Gets GlVoucherLines entity object.
     * @return the GlVoucherLines
     */
    public GlVoucherLinesImpl getGlVoucherLines() {
        return (GlVoucherLinesImpl) getEntity(ENTITY_GLVOUCHERLINES);
    }

    /**
     * Gets the attribute value for VOUCHER_LINES_SNO using the alias name VoucherLinesSno.
     * @return the VOUCHER_LINES_SNO
     */
    public Integer getVoucherLinesSno() {
        return (Integer) getAttributeInternal(VOUCHERLINESSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_LINES_SNO using the alias name VoucherLinesSno.
     * @param value value to set the VOUCHER_LINES_SNO
     */
    public void setVoucherLinesSno(Integer value) {
        setAttributeInternal(VOUCHERLINESSNO, value);
    }

    /**
     * Gets the attribute value for VOUCHER_HEADER_SNO using the alias name VoucherHeaderSno.
     * @return the VOUCHER_HEADER_SNO
     */
    public Integer getVoucherHeaderSno() {
        return (Integer) getAttributeInternal(VOUCHERHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_HEADER_SNO using the alias name VoucherHeaderSno.
     * @param value value to set the VOUCHER_HEADER_SNO
     */
    public void setVoucherHeaderSno(Integer value) {
        setAttributeInternal(VOUCHERHEADERSNO, value);
    }

    /**
     * Gets the attribute value for CHART_OF_ACCOUNT_ID using the alias name ChartOfAccountId.
     * @return the CHART_OF_ACCOUNT_ID
     */
    public Integer getChartOfAccountId() {
        return (Integer) getAttributeInternal(CHARTOFACCOUNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CHART_OF_ACCOUNT_ID using the alias name ChartOfAccountId.
     * @param value value to set the CHART_OF_ACCOUNT_ID
     */
    public void setChartOfAccountId(Integer value) {
        setAttributeInternal(CHARTOFACCOUNTID, value);
    }

    /**
     * Gets the attribute value for DEBIT using the alias name Debit.
     * @return the DEBIT
     */
    public BigDecimal getDebit() {
        return (BigDecimal) getAttributeInternal(DEBIT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEBIT using the alias name Debit.
     * @param value value to set the DEBIT
     */
    public void setDebit(BigDecimal value) {
        setAttributeInternal(DEBIT, value);
    }

    /**
     * Gets the attribute value for CREDIT using the alias name Credit.
     * @return the CREDIT
     */
    public BigDecimal getCredit() {
        return (BigDecimal) getAttributeInternal(CREDIT);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT using the alias name Credit.
     * @param value value to set the CREDIT
     */
    public void setCredit(BigDecimal value) {
        setAttributeInternal(CREDIT, value);
    }

    /**
     * Gets the attribute value for CHEQUE_NO using the alias name ChequeNo.
     * @return the CHEQUE_NO
     */
    public String getChequeNo() {
        return (String) getAttributeInternal(CHEQUENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CHEQUE_NO using the alias name ChequeNo.
     * @param value value to set the CHEQUE_NO
     */
    public void setChequeNo(String value) {
        setAttributeInternal(CHEQUENO, value);
    }

    /**
     * Gets the attribute value for NARATION using the alias name Naration.
     * @return the NARATION
     */
    public String getNaration() {
        return (String) getAttributeInternal(NARATION);
    }

    /**
     * Sets <code>value</code> as attribute value for NARATION using the alias name Naration.
     * @param value value to set the NARATION
     */
    public void setNaration(String value) {
        setAttributeInternal(NARATION, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for PROJECT_SNO using the alias name ProjectSno.
     * @return the PROJECT_SNO
     */
    public Integer getProjectSno() {
        return (Integer) getAttributeInternal(PROJECTSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_SNO using the alias name ProjectSno.
     * @param value value to set the PROJECT_SNO
     */
    public void setProjectSno(Integer value) {
        setAttributeInternal(PROJECTSNO, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @return the DEPARTMENT_ID
     */
    public BigDecimal getDepartmentId() {
        return (BigDecimal) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @param value value to set the DEPARTMENT_ID
     */
    public void setDepartmentId(BigDecimal value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for CHEQUE_DATE using the alias name ChequeDate.
     * @return the CHEQUE_DATE
     */
    public Timestamp getChequeDate() {
        return (Timestamp) getAttributeInternal(CHEQUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CHEQUE_DATE using the alias name ChequeDate.
     * @param value value to set the CHEQUE_DATE
     */
    public void setChequeDate(Timestamp value) {
        setAttributeInternal(CHEQUEDATE, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Integer getQuantity() {
        return (Integer) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Integer value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for txt_COADescription using the alias name txtCOADescription.
     * @return the txt_COADescription
     */
    public String gettxtCOADescription() {
        return (String) getAttributeInternal(TXTCOADESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_COADescription using the alias name txtCOADescription.
     * @param value value to set the txt_COADescription
     */
    public void settxtCOADescription(String value) {
        setAttributeInternal(TXTCOADESCRIPTION, value);
    }

    /**
     * Gets the attribute value for txt_COACode using the alias name txtCOACode.
     * @return the txt_COACode
     */
    public String gettxtCOACode() {
        return (String) getAttributeInternal(TXTCOACODE);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_COACode using the alias name txtCOACode.
     * @param value value to set the txt_COACode
     */
    public void settxtCOACode(String value) {
        setAttributeInternal(TXTCOACODE, value);
    }

    /**
     * Gets the attribute value for txt_Project_Name using the alias name txtProjectName.
     * @return the txt_Project_Name
     */
    public String gettxtProjectName() {
        return (String) getAttributeInternal(TXTPROJECTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Project_Name using the alias name txtProjectName.
     * @param value value to set the txt_Project_Name
     */
    public void settxtProjectName(String value) {
        setAttributeInternal(TXTPROJECTNAME, value);
    }

    /**
     * Gets the attribute value for txt_Department_Name using the alias name txtDepartmentName.
     * @return the txt_Department_Name
     */
    public String gettxtDepartmentName() {
        return (String) getAttributeInternal(TXTDEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Department_Name using the alias name txtDepartmentName.
     * @param value value to set the txt_Department_Name
     */
    public void settxtDepartmentName(String value) {
        setAttributeInternal(TXTDEPARTMENTNAME, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlVoucherHeaderVO.
     */
    public Row getGlVoucherHeaderVO() {
        return (Row) getAttributeInternal(GLVOUCHERHEADERVO);
    }

    /**
     * Sets the master-detail link GlVoucherHeaderVO between this object and <code>value</code>.
     */
    public void setGlVoucherHeaderVO(Row value) {
        setAttributeInternal(GLVOUCHERHEADERVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlChartOfAccountsVO.
     */
    public Row getGlChartOfAccountsVO() {
        return (Row) getAttributeInternal(GLCHARTOFACCOUNTSVO);
    }

    /**
     * Sets the master-detail link GlChartOfAccountsVO between this object and <code>value</code>.
     */
    public void setGlChartOfAccountsVO(Row value) {
        setAttributeInternal(GLCHARTOFACCOUNTSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlProjectsVO.
     */
    public Row getGlProjectsVO() {
        return (Row) getAttributeInternal(GLPROJECTSVO);
    }

    /**
     * Sets the master-detail link GlProjectsVO between this object and <code>value</code>.
     */
    public void setGlProjectsVO(Row value) {
        setAttributeInternal(GLPROJECTSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyVO.
     */
    public Row getAdminCompanyVO() {
        return (Row) getAttributeInternal(ADMINCOMPANYVO);
    }

    /**
     * Sets the master-detail link AdminCompanyVO between this object and <code>value</code>.
     */
    public void setAdminCompanyVO(Row value) {
        setAttributeInternal(ADMINCOMPANYVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlChartOfAccountsQVO.
     */
    public RowSet getAccGlChartOfAccountsQVO() {
        RowSet rs=  (RowSet) getAttributeInternal(ACCGLCHARTOFACCOUNTSQVO);
        rs.setNamedWhereClauseParam("P_ADF_COMPANY_ID", getGlVoucherHeaderVO().getAttribute("CompanyId"));
        rs.executeQuery();
        return rs;
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlProjectsVO.
     */
    public RowSet getAccGlProjectsVO() {
        RowSet rs=(RowSet)getAttributeInternal(ACCGLPROJECTSVO);
        rs.setNamedWhereClauseParam("P_ADF_COMPANY_ID", getGlVoucherHeaderVO().getAttribute("CompanyId"));
        rs.executeQuery();
        return rs;
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminDepartLinCompanyVO.
     */
    public RowSet getAccAdminDepartLinCompanyVO() {
        RowSet rs=(RowSet)getAttributeInternal(ACCADMINDEPARTLINCOMPANYVO);
        rs.setNamedWhereClauseParam("P_ADF_COMP_CODE", getGlVoucherHeaderVO().getAttribute("CompanyId"));
        rs.setNamedWhereClauseParam("P_ADF_USER_ID", erpglobals.modelglobals.ERPGlobalPLSQLClass.doGetModelUserSno());
        rs.executeQuery();
        
        return rs;
    }
}

