package erpfms.modelfms.fmsvo;

import erpfms.modelfms.fmsvo.common.GlVoucherLinesVO;

import erpglobals.modelglobals.ERPViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 26 17:54:25 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlVoucherLinesVOImpl extends ERPViewObjectImpl implements GlVoucherLinesVO {
    /**
     * This is the default constructor (do not remove).
     */
    public GlVoucherLinesVOImpl() {
    }
    @Override
    public void executeEmptyRowSet() {
        // TODO Implement this method
        super.executeEmptyRowSet();
    }
}

