package erpfms.modelfms.fmsqvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 16 16:01:31 PKT 2020
// ---------------------------------------------------------------------
public interface GlPeriodForUserRightsQVORow extends Row {
    void doErpAssignSinglePeriodToUser();
}

