package erpfms.modelfms.fmsqvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 16 13:09:05 PKT 2020
// ---------------------------------------------------------------------
public interface GlPeriodForUserRightsQVO extends ViewObject {
    void doErpAssignAllPeriodToUser();
}

