package erpfms.modelfms.fmsqvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 09 13:48:44 PKT 2020
// ---------------------------------------------------------------------
public interface SysUsersForAssignCOAUserRightsQVO extends ViewObject {
    void doErpAssignAllUserToCOA();
}

