package erpfms.modelfms.fmsqvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 09 13:48:36 PKT 2020
// ---------------------------------------------------------------------
public interface SysUsersForAssignCOAUserRightsQVORow extends Row {
    void doErpAssignSingleUserToCOA();
}

