package erpfms.modelfms.fmsqvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 10 20:03:03 PKT 2020
// ---------------------------------------------------------------------
public interface SysUsersForAssignVoucherTypeUserRightsQVORow extends Row {
    void doErpAssignSingleUserToVoucherType();
}

