package erpfms.modelfms.fmsqvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 10 20:58:26 PKT 2020
// ---------------------------------------------------------------------
public interface SysUsersForAssignVoucherTypeUserRightsQVO extends ViewObject {
    void doErpAssignAllUserToVoucherType();
}

