package erpfms.modelfms.fmseo;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 14 12:30:43 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlBatchSetupImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BatchId,
        BatchDescription,
        BatchDate,
        Remarks,
        BatchCode,
        BatchShortName,
        CompanyId,
        CreatedBy,
        CreatedDate,
        GlobalCompanyId,
        LastUpdatedBy,
        LastUpdatedDate,
        IsActive;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BATCHID = AttributesEnum.BatchId.index();
    public static final int BATCHDESCRIPTION = AttributesEnum.BatchDescription.index();
    public static final int BATCHDATE = AttributesEnum.BatchDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int BATCHCODE = AttributesEnum.BatchCode.index();
    public static final int BATCHSHORTNAME = AttributesEnum.BatchShortName.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlBatchSetupImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpfms.modelfms.fmseo.GlBatchSetup");
    }


    /**
     * Gets the attribute value for BatchId, using the alias name BatchId.
     * @return the value of BatchId
     */
    public Integer getBatchId() {
        return (Integer) getAttributeInternal(BATCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchId.
     * @param value value to set the BatchId
     */
    public void setBatchId(Integer value) {
        setAttributeInternal(BATCHID, value);
    }

    /**
     * Gets the attribute value for BatchDescription, using the alias name BatchDescription.
     * @return the value of BatchDescription
     */
    public String getBatchDescription() {
        return (String) getAttributeInternal(BATCHDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchDescription.
     * @param value value to set the BatchDescription
     */
    public void setBatchDescription(String value) {
        setAttributeInternal(BATCHDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for BatchDate, using the alias name BatchDate.
     * @return the value of BatchDate
     */
    public Timestamp getBatchDate() {
        return (Timestamp) getAttributeInternal(BATCHDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchDate.
     * @param value value to set the BatchDate
     */
    public void setBatchDate(Timestamp value) {
        setAttributeInternal(BATCHDATE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for BatchCode, using the alias name BatchCode.
     * @return the value of BatchCode
     */
    public Integer getBatchCode() {
        return (Integer) getAttributeInternal(BATCHCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchCode.
     * @param value value to set the BatchCode
     */
    public void setBatchCode(Integer value) {
        setAttributeInternal(BATCHCODE, value);
    }

    /**
     * Gets the attribute value for BatchShortName, using the alias name BatchShortName.
     * @return the value of BatchShortName
     */
    public String getBatchShortName() {
        return (String) getAttributeInternal(BATCHSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchShortName.
     * @param value value to set the BatchShortName
     */
    public void setBatchShortName(String value) {
        setAttributeInternal(BATCHSHORTNAME, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for GlobalCompanyId, using the alias name GlobalCompanyId.
     * @return the value of GlobalCompanyId
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompanyId.
     * @param value value to set the GlobalCompanyId
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }


    /**
     * @param batchId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer batchId) {
        return new Key(new Object[] { batchId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        if (operation==DML_INSERT ) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "BATCH_ID",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(BATCHID,  Integer.parseInt(result));
           result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "BATCH_CODE",this.getEntityDef().getSource(), "COMPANY_ID", getCompanyId().toString());
           populateAttributeAsChanged(BATCHCODE,  Integer.parseInt(result));

        }
        
        super.doDML(operation, e);
    }
}

