package erpfms.modelfms.fmseo;

import erpglobals.modelglobals.ERPEntityImpl;

import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 14 16:23:38 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlBudgetImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BudgetSno,
        BudgetShortCode,
        BudgetShortName,
        BudgetName,
        DocumentDate,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        IsActive,
        FiscalYearSno,
        StartPeriodSno,
        PeriodStartDate,
        EndPeriodSno,
        PeriodEndDate,
        SupervisedBy,
        SupervisedDate,
        IsSupervised,
        UnSupervisedBy,
        UnSupervisedDate,
        IsUnsupervised,
        CompanyId,
        GlobalCompanyId,
        txtStartPeriodName,
        txtEndPeriodName,
        txtFiscalYearName,
        txtFiscalYearStart,
        txtFiscalYearEnd,
        GlPeriods,
        GlPeriods1,
        GlFiscalYear;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUDGETSNO = AttributesEnum.BudgetSno.index();
    public static final int BUDGETSHORTCODE = AttributesEnum.BudgetShortCode.index();
    public static final int BUDGETSHORTNAME = AttributesEnum.BudgetShortName.index();
    public static final int BUDGETNAME = AttributesEnum.BudgetName.index();
    public static final int DOCUMENTDATE = AttributesEnum.DocumentDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int FISCALYEARSNO = AttributesEnum.FiscalYearSno.index();
    public static final int STARTPERIODSNO = AttributesEnum.StartPeriodSno.index();
    public static final int PERIODSTARTDATE = AttributesEnum.PeriodStartDate.index();
    public static final int ENDPERIODSNO = AttributesEnum.EndPeriodSno.index();
    public static final int PERIODENDDATE = AttributesEnum.PeriodEndDate.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int TXTSTARTPERIODNAME = AttributesEnum.txtStartPeriodName.index();
    public static final int TXTENDPERIODNAME = AttributesEnum.txtEndPeriodName.index();
    public static final int TXTFISCALYEARNAME = AttributesEnum.txtFiscalYearName.index();
    public static final int TXTFISCALYEARSTART = AttributesEnum.txtFiscalYearStart.index();
    public static final int TXTFISCALYEAREND = AttributesEnum.txtFiscalYearEnd.index();
    public static final int GLPERIODS = AttributesEnum.GlPeriods.index();
    public static final int GLPERIODS1 = AttributesEnum.GlPeriods1.index();
    public static final int GLFISCALYEAR = AttributesEnum.GlFiscalYear.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlBudgetImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpfms.modelfms.fmseo.GlBudget");
    }


    /**
     * Gets the attribute value for BudgetSno, using the alias name BudgetSno.
     * @return the value of BudgetSno
     */
    public Integer getBudgetSno() {
        return (Integer) getAttributeInternal(BUDGETSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetSno.
     * @param value value to set the BudgetSno
     */
    public void setBudgetSno(Integer value) {
        setAttributeInternal(BUDGETSNO, value);
    }

    /**
     * Gets the attribute value for BudgetShortCode, using the alias name BudgetShortCode.
     * @return the value of BudgetShortCode
     */
    public Integer getBudgetShortCode() {
        return (Integer) getAttributeInternal(BUDGETSHORTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetShortCode.
     * @param value value to set the BudgetShortCode
     */
    public void setBudgetShortCode(Integer value) {
        setAttributeInternal(BUDGETSHORTCODE, value);
    }

    /**
     * Gets the attribute value for BudgetShortName, using the alias name BudgetShortName.
     * @return the value of BudgetShortName
     */
    public String getBudgetShortName() {
        return (String) getAttributeInternal(BUDGETSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetShortName.
     * @param value value to set the BudgetShortName
     */
    public void setBudgetShortName(String value) {
        setAttributeInternal(BUDGETSHORTNAME, value);
    }

    /**
     * Gets the attribute value for BudgetName, using the alias name BudgetName.
     * @return the value of BudgetName
     */
    public String getBudgetName() {
        return (String) getAttributeInternal(BUDGETNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetName.
     * @param value value to set the BudgetName
     */
    public void setBudgetName(String value) {
        setAttributeInternal(BUDGETNAME, value);
    }

    /**
     * Gets the attribute value for DocumentDate, using the alias name DocumentDate.
     * @return the value of DocumentDate
     */
    public Date getDocumentDate() {
        return (Date) getAttributeInternal(DOCUMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentDate.
     * @param value value to set the DocumentDate
     */
    public void setDocumentDate(Date value) {
        setAttributeInternal(DOCUMENTDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for FiscalYearSno, using the alias name FiscalYearSno.
     * @return the value of FiscalYearSno
     */
    public Integer getFiscalYearSno() {
        return (Integer) getAttributeInternal(FISCALYEARSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FiscalYearSno.
     * @param value value to set the FiscalYearSno
     */
    public void setFiscalYearSno(Integer value) {
        setAttributeInternal(FISCALYEARSNO, value);
    }

    /**
     * Gets the attribute value for StartPeriodSno, using the alias name StartPeriodSno.
     * @return the value of StartPeriodSno
     */
    public Integer getStartPeriodSno() {
        return (Integer) getAttributeInternal(STARTPERIODSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartPeriodSno.
     * @param value value to set the StartPeriodSno
     */
    public void setStartPeriodSno(Integer value) {
        setAttributeInternal(STARTPERIODSNO, value);
    }

    /**
     * Gets the attribute value for PeriodStartDate, using the alias name PeriodStartDate.
     * @return the value of PeriodStartDate
     */
    public Date getPeriodStartDate() {
        return (Date) getAttributeInternal(PERIODSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodStartDate.
     * @param value value to set the PeriodStartDate
     */
    public void setPeriodStartDate(Date value) {
        setAttributeInternal(PERIODSTARTDATE, value);
    }

    /**
     * Gets the attribute value for EndPeriodSno, using the alias name EndPeriodSno.
     * @return the value of EndPeriodSno
     */
    public Integer getEndPeriodSno() {
        return (Integer) getAttributeInternal(ENDPERIODSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndPeriodSno.
     * @param value value to set the EndPeriodSno
     */
    public void setEndPeriodSno(Integer value) {
        setAttributeInternal(ENDPERIODSNO, value);
    }

    /**
     * Gets the attribute value for PeriodEndDate, using the alias name PeriodEndDate.
     * @return the value of PeriodEndDate
     */
    public Date getPeriodEndDate() {
        return (Date) getAttributeInternal(PERIODENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodEndDate.
     * @param value value to set the PeriodEndDate
     */
    public void setPeriodEndDate(Date value) {
        setAttributeInternal(PERIODENDDATE, value);
    }

    /**
     * Gets the attribute value for SupervisedBy, using the alias name SupervisedBy.
     * @return the value of SupervisedBy
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedBy.
     * @param value value to set the SupervisedBy
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for SupervisedDate, using the alias name SupervisedDate.
     * @return the value of SupervisedDate
     */
    public Date getSupervisedDate() {
        return (Date) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedDate.
     * @param value value to set the SupervisedDate
     */
    public void setSupervisedDate(Date value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IsSupervised, using the alias name IsSupervised.
     * @return the value of IsSupervised
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSupervised.
     * @param value value to set the IsSupervised
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for UnSupervisedBy, using the alias name UnSupervisedBy.
     * @return the value of UnSupervisedBy
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedBy.
     * @param value value to set the UnSupervisedBy
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for UnSupervisedDate, using the alias name UnSupervisedDate.
     * @return the value of UnSupervisedDate
     */
    public Date getUnSupervisedDate() {
        return (Date) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedDate.
     * @param value value to set the UnSupervisedDate
     */
    public void setUnSupervisedDate(Date value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IsUnsupervised, using the alias name IsUnsupervised.
     * @return the value of IsUnsupervised
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsUnsupervised.
     * @param value value to set the IsUnsupervised
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for GlobalCompanyId, using the alias name GlobalCompanyId.
     * @return the value of GlobalCompanyId
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompanyId.
     * @param value value to set the GlobalCompanyId
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }


    /**
     * Gets the attribute value for txtStartPeriodName, using the alias name txtStartPeriodName.
     * @return the value of txtStartPeriodName
     */
    public String gettxtStartPeriodName() {
        return (String) getAttributeInternal(TXTSTARTPERIODNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtStartPeriodName.
     * @param value value to set the txtStartPeriodName
     */
    public void settxtStartPeriodName(String value) {
        setAttributeInternal(TXTSTARTPERIODNAME, value);
    }

    /**
     * Gets the attribute value for txtEndPeriodName, using the alias name txtEndPeriodName.
     * @return the value of txtEndPeriodName
     */
    public String gettxtEndPeriodName() {
        return (String) getAttributeInternal(TXTENDPERIODNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtEndPeriodName.
     * @param value value to set the txtEndPeriodName
     */
    public void settxtEndPeriodName(String value) {
        setAttributeInternal(TXTENDPERIODNAME, value);
    }

    /**
     * Gets the attribute value for txtFiscalYearName, using the alias name txtFiscalYearName.
     * @return the value of txtFiscalYearName
     */
    public String gettxtFiscalYearName() {
        return (String) getAttributeInternal(TXTFISCALYEARNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtFiscalYearName.
     * @param value value to set the txtFiscalYearName
     */
    public void settxtFiscalYearName(String value) {
        setAttributeInternal(TXTFISCALYEARNAME, value);
    }

    /**
     * Gets the attribute value for txtFiscalYearStart, using the alias name txtFiscalYearStart.
     * @return the value of txtFiscalYearStart
     */
    public Date gettxtFiscalYearStart() {
        return (Date) getAttributeInternal(TXTFISCALYEARSTART);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtFiscalYearStart.
     * @param value value to set the txtFiscalYearStart
     */
    public void settxtFiscalYearStart(Date value) {
        setAttributeInternal(TXTFISCALYEARSTART, value);
    }

    /**
     * Gets the attribute value for txtFiscalYearEnd, using the alias name txtFiscalYearEnd.
     * @return the value of txtFiscalYearEnd
     */
    public Date gettxtFiscalYearEnd() {
        return (Date) getAttributeInternal(TXTFISCALYEAREND);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtFiscalYearEnd.
     * @param value value to set the txtFiscalYearEnd
     */
    public void settxtFiscalYearEnd(Date value) {
        setAttributeInternal(TXTFISCALYEAREND, value);
    }

    /**
     * @return the associated entity GlPeriodsImpl.
     */
    public GlPeriodsImpl getGlPeriods() {
        return (GlPeriodsImpl) getAttributeInternal(GLPERIODS);
    }

    /**
     * Sets <code>value</code> as the associated entity GlPeriodsImpl.
     */
    public void setGlPeriods(GlPeriodsImpl value) {
        setAttributeInternal(GLPERIODS, value);
    }

    /**
     * @return the associated entity GlPeriodsImpl.
     */
    public GlPeriodsImpl getGlPeriods1() {
        return (GlPeriodsImpl) getAttributeInternal(GLPERIODS1);
    }

    /**
     * Sets <code>value</code> as the associated entity GlPeriodsImpl.
     */
    public void setGlPeriods1(GlPeriodsImpl value) {
        setAttributeInternal(GLPERIODS1, value);
    }


    /**
     * @return the associated entity GlFiscalYearImpl.
     */
    public GlFiscalYearImpl getGlFiscalYear() {
        return (GlFiscalYearImpl) getAttributeInternal(GLFISCALYEAR);
    }

    /**
     * Sets <code>value</code> as the associated entity GlFiscalYearImpl.
     */
    public void setGlFiscalYear(GlFiscalYearImpl value) {
        setAttributeInternal(GLFISCALYEAR, value);
    }


    /**
     * @param budgetSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer budgetSno) {
        return new Key(new Object[] { budgetSno });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        if (operation == DML_INSERT) {
            
            String result =
                ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "BUDGET_SNO",
                                                              this.getEntityDef().getSource(), null, null);

            populateAttributeAsChanged(BUDGETSNO, Integer.parseInt(result));
            result =
                ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "BUDGET_SHORT_CODE",
                                                              this.getEntityDef().getSource(), "COMPANY_ID",
                                                              getCompanyId().toString());
            populateAttributeAsChanged(BUDGETSHORTCODE, Integer.parseInt(result));

        }        
        super.doDML(operation, e);
    }
}

