package erpfms.modelfms.fmseo;

import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 28 23:41:57 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlTaxTypeImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TaxTypeSno,
        TaxTypeCode,
        TaxTypeShortName,
        OpenDate,
        TaxTypeName,
        GlobalCompanyId,
        ChartOfAccountId,
        CompanyId,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        IsStandard,
        IsLocationWise,
        IsCustCategoryWise,
        IsCustTypeWise,
        IsExempted,
        IsProduct,
        IsSupervised,
        SupervisedDate,
        IsUnsupervised,
        UnSupervisedDate,
        SupervisedBy,
        UnSupervisedBy,
        IsActive;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TAXTYPESNO = AttributesEnum.TaxTypeSno.index();
    public static final int TAXTYPECODE = AttributesEnum.TaxTypeCode.index();
    public static final int TAXTYPESHORTNAME = AttributesEnum.TaxTypeShortName.index();
    public static final int OPENDATE = AttributesEnum.OpenDate.index();
    public static final int TAXTYPENAME = AttributesEnum.TaxTypeName.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int CHARTOFACCOUNTID = AttributesEnum.ChartOfAccountId.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ISSTANDARD = AttributesEnum.IsStandard.index();
    public static final int ISLOCATIONWISE = AttributesEnum.IsLocationWise.index();
    public static final int ISCUSTCATEGORYWISE = AttributesEnum.IsCustCategoryWise.index();
    public static final int ISCUSTTYPEWISE = AttributesEnum.IsCustTypeWise.index();
    public static final int ISEXEMPTED = AttributesEnum.IsExempted.index();
    public static final int ISPRODUCT = AttributesEnum.IsProduct.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlTaxTypeImpl() {
    }

    /**
     * Gets the attribute value for TaxTypeSno, using the alias name TaxTypeSno.
     * @return the value of TaxTypeSno
     */
    public Integer getTaxTypeSno() {
        return (Integer) getAttributeInternal(TAXTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxTypeSno.
     * @param value value to set the TaxTypeSno
     */
    public void setTaxTypeSno(Integer value) {
        setAttributeInternal(TAXTYPESNO, value);
    }

    /**
     * Gets the attribute value for TaxTypeCode, using the alias name TaxTypeCode.
     * @return the value of TaxTypeCode
     */
    public Integer getTaxTypeCode() {
        return (Integer) getAttributeInternal(TAXTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxTypeCode.
     * @param value value to set the TaxTypeCode
     */
    public void setTaxTypeCode(Integer value) {
        setAttributeInternal(TAXTYPECODE, value);
    }

    /**
     * Gets the attribute value for TaxTypeShortName, using the alias name TaxTypeShortName.
     * @return the value of TaxTypeShortName
     */
    public String getTaxTypeShortName() {
        return (String) getAttributeInternal(TAXTYPESHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxTypeShortName.
     * @param value value to set the TaxTypeShortName
     */
    public void setTaxTypeShortName(String value) {
        setAttributeInternal(TAXTYPESHORTNAME, value);
    }

    /**
     * Gets the attribute value for OpenDate, using the alias name OpenDate.
     * @return the value of OpenDate
     */
    public Timestamp getOpenDate() {
        return (Timestamp) getAttributeInternal(OPENDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpenDate.
     * @param value value to set the OpenDate
     */
    public void setOpenDate(Timestamp value) {
        setAttributeInternal(OPENDATE, value);
    }

    /**
     * Gets the attribute value for TaxTypeName, using the alias name TaxTypeName.
     * @return the value of TaxTypeName
     */
    public String getTaxTypeName() {
        return (String) getAttributeInternal(TAXTYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxTypeName.
     * @param value value to set the TaxTypeName
     */
    public void setTaxTypeName(String value) {
        setAttributeInternal(TAXTYPENAME, value);
    }

    /**
     * Gets the attribute value for GlobalCompanyId, using the alias name GlobalCompanyId.
     * @return the value of GlobalCompanyId
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompanyId.
     * @param value value to set the GlobalCompanyId
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for ChartOfAccountId, using the alias name ChartOfAccountId.
     * @return the value of ChartOfAccountId
     */
    public Integer getChartOfAccountId() {
        return (Integer) getAttributeInternal(CHARTOFACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChartOfAccountId.
     * @param value value to set the ChartOfAccountId
     */
    public void setChartOfAccountId(Integer value) {
        setAttributeInternal(CHARTOFACCOUNTID, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for IsStandard, using the alias name IsStandard.
     * @return the value of IsStandard
     */
    public String getIsStandard() {
        return (String) getAttributeInternal(ISSTANDARD);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsStandard.
     * @param value value to set the IsStandard
     */
    public void setIsStandard(String value) {
        setAttributeInternal(ISSTANDARD, value);
    }

    /**
     * Gets the attribute value for IsLocationWise, using the alias name IsLocationWise.
     * @return the value of IsLocationWise
     */
    public String getIsLocationWise() {
        return (String) getAttributeInternal(ISLOCATIONWISE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsLocationWise.
     * @param value value to set the IsLocationWise
     */
    public void setIsLocationWise(String value) {
        setAttributeInternal(ISLOCATIONWISE, value);
    }

    /**
     * Gets the attribute value for IsCustCategoryWise, using the alias name IsCustCategoryWise.
     * @return the value of IsCustCategoryWise
     */
    public String getIsCustCategoryWise() {
        return (String) getAttributeInternal(ISCUSTCATEGORYWISE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsCustCategoryWise.
     * @param value value to set the IsCustCategoryWise
     */
    public void setIsCustCategoryWise(String value) {
        setAttributeInternal(ISCUSTCATEGORYWISE, value);
    }

    /**
     * Gets the attribute value for IsCustTypeWise, using the alias name IsCustTypeWise.
     * @return the value of IsCustTypeWise
     */
    public String getIsCustTypeWise() {
        return (String) getAttributeInternal(ISCUSTTYPEWISE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsCustTypeWise.
     * @param value value to set the IsCustTypeWise
     */
    public void setIsCustTypeWise(String value) {
        setAttributeInternal(ISCUSTTYPEWISE, value);
    }

    /**
     * Gets the attribute value for IsExempted, using the alias name IsExempted.
     * @return the value of IsExempted
     */
    public String getIsExempted() {
        return (String) getAttributeInternal(ISEXEMPTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsExempted.
     * @param value value to set the IsExempted
     */
    public void setIsExempted(String value) {
        setAttributeInternal(ISEXEMPTED, value);
    }

    /**
     * Gets the attribute value for IsProduct, using the alias name IsProduct.
     * @return the value of IsProduct
     */
    public String getIsProduct() {
        return (String) getAttributeInternal(ISPRODUCT);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsProduct.
     * @param value value to set the IsProduct
     */
    public void setIsProduct(String value) {
        setAttributeInternal(ISPRODUCT, value);
    }

    /**
     * Gets the attribute value for IsSupervised, using the alias name IsSupervised.
     * @return the value of IsSupervised
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSupervised.
     * @param value value to set the IsSupervised
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for SupervisedDate, using the alias name SupervisedDate.
     * @return the value of SupervisedDate
     */
    public Timestamp getSupervisedDate() {
        return (Timestamp) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedDate.
     * @param value value to set the SupervisedDate
     */
    public void setSupervisedDate(Timestamp value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IsUnsupervised, using the alias name IsUnsupervised.
     * @return the value of IsUnsupervised
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsUnsupervised.
     * @param value value to set the IsUnsupervised
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for UnSupervisedDate, using the alias name UnSupervisedDate.
     * @return the value of UnSupervisedDate
     */
    public Timestamp getUnSupervisedDate() {
        return (Timestamp) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedDate.
     * @param value value to set the UnSupervisedDate
     */
    public void setUnSupervisedDate(Timestamp value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for SupervisedBy, using the alias name SupervisedBy.
     * @return the value of SupervisedBy
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedBy.
     * @param value value to set the SupervisedBy
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for UnSupervisedBy, using the alias name UnSupervisedBy.
     * @return the value of UnSupervisedBy
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedBy.
     * @param value value to set the UnSupervisedBy
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * @param taxTypeSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer taxTypeSno) {
        return new Key(new Object[] { taxTypeSno });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpfms.modelfms.fmseo.GlTaxType");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            
            String result =
                ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "TAX_TYPE_SNO",
                                                              this.getEntityDef().getSource(), null, null);

            populateAttributeAsChanged(TAXTYPESNO, Integer.parseInt(result));
            result =
                ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "TAX_TYPE_CODE",
                                                              this.getEntityDef().getSource(), "COMPANY_ID",
                                                              getCompanyId().toString());
            populateAttributeAsChanged(TAXTYPECODE, Integer.parseInt(result));

        }        
        super.doDML(operation, e);
    }
}

