package erpfms.modelfms.fmseo;

import erpadm.modeladm.admeo.SysUsersImpl;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 08 22:59:27 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlUserVoucherTypeImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserVoucherTypeSno,
        UserId,
        VoucherTypeId,
        IsActive,
        IsDefault,
        CompanyId,
        GlobalCompanyId,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        GlVoucherTypes,
        SysUsers;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERVOUCHERTYPESNO = AttributesEnum.UserVoucherTypeSno.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int VOUCHERTYPEID = AttributesEnum.VoucherTypeId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int ISDEFAULT = AttributesEnum.IsDefault.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int GLVOUCHERTYPES = AttributesEnum.GlVoucherTypes.index();
    public static final int SYSUSERS = AttributesEnum.SysUsers.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlUserVoucherTypeImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpfms.modelfms.fmseo.GlUserVoucherType");
    }


    /**
     * Gets the attribute value for UserVoucherTypeSno, using the alias name UserVoucherTypeSno.
     * @return the value of UserVoucherTypeSno
     */
    public Integer getUserVoucherTypeSno() {
        return (Integer) getAttributeInternal(USERVOUCHERTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserVoucherTypeSno.
     * @param value value to set the UserVoucherTypeSno
     */
    public void setUserVoucherTypeSno(Integer value) {
        setAttributeInternal(USERVOUCHERTYPESNO, value);
    }

    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the value of UserId
     */
    public Integer getUserId() {
        return (Integer) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(Integer value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for VoucherTypeId, using the alias name VoucherTypeId.
     * @return the value of VoucherTypeId
     */
    public Integer getVoucherTypeId() {
        return (Integer) getAttributeInternal(VOUCHERTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherTypeId.
     * @param value value to set the VoucherTypeId
     */
    public void setVoucherTypeId(Integer value) {
        setAttributeInternal(VOUCHERTYPEID, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for IsDefault, using the alias name IsDefault.
     * @return the value of IsDefault
     */
    public String getIsDefault() {
        return (String) getAttributeInternal(ISDEFAULT);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsDefault.
     * @param value value to set the IsDefault
     */
    public void setIsDefault(String value) {
        setAttributeInternal(ISDEFAULT, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for GlobalCompanyId, using the alias name GlobalCompanyId.
     * @return the value of GlobalCompanyId
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompanyId.
     * @param value value to set the GlobalCompanyId
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }


    /**
     * @return the associated entity GlVoucherTypesImpl.
     */
    public GlVoucherTypesImpl getGlVoucherTypes() {
        return (GlVoucherTypesImpl) getAttributeInternal(GLVOUCHERTYPES);
    }

    /**
     * Sets <code>value</code> as the associated entity GlVoucherTypesImpl.
     */
    public void setGlVoucherTypes(GlVoucherTypesImpl value) {
        setAttributeInternal(GLVOUCHERTYPES, value);
    }


    /**
     * @return the associated entity erpadm.modeladm.admeo.SysUsersImpl.
     */
    public SysUsersImpl getSysUsers() {
        return (SysUsersImpl) getAttributeInternal(SYSUSERS);
    }

    /**
     * Sets <code>value</code> as the associated entity erpadm.modeladm.admeo.SysUsersImpl.
     */
    public void setSysUsers(SysUsersImpl value) {
        setAttributeInternal(SYSUSERS, value);
    }


    /**
     * @param userVoucherTypeSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer userVoucherTypeSno) {
        return new Key(new Object[] { userVoucherTypeSno });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "USER_VOUCHER_TYPE_SNO",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(USERVOUCHERTYPESNO,  Integer.parseInt(result));
            
       }
        super.doDML(operation, e);
    }
}

