package erpfms.modelfms.fmseo;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 07 20:08:12 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlVoucherTypesImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        VoucherTypeId,
        CreatedBy,
        LastUpdatedBy,
        VoucherTypeCode,
        VoucherTypeName,
        CreatedDate,
        LastUpdatedDate,
        CompanyId,
        GlobalCompanyId,
        VoucherCategorySno,
        IsActive,
        GlVouchers,
        GlVoucherHeader,
        GlUserVoucherType,
        AccGlVoucherTypesSEQ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int VOUCHERTYPEID = AttributesEnum.VoucherTypeId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int VOUCHERTYPECODE = AttributesEnum.VoucherTypeCode.index();
    public static final int VOUCHERTYPENAME = AttributesEnum.VoucherTypeName.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int VOUCHERCATEGORYSNO = AttributesEnum.VoucherCategorySno.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int GLVOUCHERS = AttributesEnum.GlVouchers.index();
    public static final int GLVOUCHERHEADER = AttributesEnum.GlVoucherHeader.index();
    public static final int GLUSERVOUCHERTYPE = AttributesEnum.GlUserVoucherType.index();
    public static final int ACCGLVOUCHERTYPESSEQ = AttributesEnum.AccGlVoucherTypesSEQ.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlVoucherTypesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpfms.modelfms.fmseo.GlVoucherTypes");
    }


    /**
     * Gets the attribute value for VoucherTypeId, using the alias name VoucherTypeId.
     * @return the value of VoucherTypeId
     */
    public Integer getVoucherTypeId() {
        return (Integer) getAttributeInternal(VOUCHERTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherTypeId.
     * @param value value to set the VoucherTypeId
     */
    public void setVoucherTypeId(Integer value) {
        setAttributeInternal(VOUCHERTYPEID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for VoucherTypeCode, using the alias name VoucherTypeCode.
     * @return the value of VoucherTypeCode
     */
    public Integer getVoucherTypeCode() {
        return (Integer) getAttributeInternal(VOUCHERTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherTypeCode.
     * @param value value to set the VoucherTypeCode
     */
    public void setVoucherTypeCode(Integer value) {
        setAttributeInternal(VOUCHERTYPECODE, value);
    }

    /**
     * Gets the attribute value for VoucherTypeName, using the alias name VoucherTypeName.
     * @return the value of VoucherTypeName
     */
    public String getVoucherTypeName() {
        return (String) getAttributeInternal(VOUCHERTYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherTypeName.
     * @param value value to set the VoucherTypeName
     */
    public void setVoucherTypeName(String value) {
        setAttributeInternal(VOUCHERTYPENAME, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for GlobalCompanyId, using the alias name GlobalCompanyId.
     * @return the value of GlobalCompanyId
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompanyId.
     * @param value value to set the GlobalCompanyId
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for VoucherCategorySno, using the alias name VoucherCategorySno.
     * @return the value of VoucherCategorySno
     */
    public Integer getVoucherCategorySno() {
        return (Integer) getAttributeInternal(VOUCHERCATEGORYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherCategorySno.
     * @param value value to set the VoucherCategorySno
     */
    public void setVoucherCategorySno(Integer value) {
        setAttributeInternal(VOUCHERCATEGORYSNO, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getGlVouchers() {
        return (RowIterator) getAttributeInternal(GLVOUCHERS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getGlVoucherHeader() {
        return (RowIterator) getAttributeInternal(GLVOUCHERHEADER);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getGlUserVoucherType() {
        return (RowIterator) getAttributeInternal(GLUSERVOUCHERTYPE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlVoucherTypesSEQ.
     */
    public RowSet getAccGlVoucherTypesSEQ() {
        return (RowSet) getAttributeInternal(ACCGLVOUCHERTYPESSEQ);
    }


    /**
     * @param voucherTypeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer voucherTypeId) {
        return new Key(new Object[] { voucherTypeId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "VOUCHER_TYPE_ID",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(VOUCHERTYPEID, Integer.parseInt(result));
           result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "VOUCHER_TYPE_CODE",this.getEntityDef().getSource(), "COMPANY_ID", getCompanyId().toString());
           populateAttributeAsChanged(VOUCHERTYPECODE,  Integer.parseInt(result));
           
        }  
        super.doDML(operation, e);
    }
}

