package erpfms.modelfms.fmseo;

import erpadm.modeladm.admeo.AdminCompanyImpl;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.math.BigDecimal;

import java.math.BigInteger;

import java.sql.Timestamp;

import java.text.SimpleDateFormat;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 14 10:48:58 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlVoucherHeaderImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        VoucherHeaderSno,
        VoucherTypeId,
        VoucherHeaderCode,
        VoucherDate,
        Remarks,
        BatchId,
        CreatedBy,
        LastUpdatedBy,
        SupervisedBy,
        SupervisedDate,
        IsSupervised,
        CompanyId,
        CurrencySno,
        ExchangeRate,
        TempProjectId,
        FileName,
        ReversedBy,
        ReversedDate,
        ReversedVoucherId,
        UnSupervisedBy,
        UnSupervisedDate,
        SourceDocumentSno,
        CreatedDate,
        LastUpdatedDate,
        PeriodSno,
        PeriodStartDate,
        PeriodEndDate,
        FiscalYearSno,
        SourceDocumentType,
        TempDepartmentId,
        LocationId,
        ReferenceNo,
        GlobalCompanyId,
        txtLocationName,
        txtVoucherTypeName,
        txtPeriodName,
        txtProjectName,
        txtTempDepartmentName,
        VoucherCategorySno,
        txtSumDebit,
        txtSumCredit,
        IsUnsupervised,
        YearDigit,
        MonthDigit,
        VoucherNoPrefix,
        IsReversed,
        ReverseFiscalYearSno,
        ReversePeriodDate,
        ReversePeriodSno,
        ReversePeriodEndDate,
        ReversePeriodStartDate,
        ReverseReason,
        txtReverseVoucherCode,
        ReversedVoucherCode,
        GlInstallmentKnockoff,
        GlVoucherAccounts,
        GlVoucherTypes,
        AdminCompany,
        GlPeriods,
        GlProjects,
        GlVoucherLines,
        AdminCompany1,
        AccGlParameterVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int VOUCHERHEADERSNO = AttributesEnum.VoucherHeaderSno.index();
    public static final int VOUCHERTYPEID = AttributesEnum.VoucherTypeId.index();
    public static final int VOUCHERHEADERCODE = AttributesEnum.VoucherHeaderCode.index();
    public static final int VOUCHERDATE = AttributesEnum.VoucherDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int BATCHID = AttributesEnum.BatchId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int CURRENCYSNO = AttributesEnum.CurrencySno.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int TEMPPROJECTID = AttributesEnum.TempProjectId.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int REVERSEDBY = AttributesEnum.ReversedBy.index();
    public static final int REVERSEDDATE = AttributesEnum.ReversedDate.index();
    public static final int REVERSEDVOUCHERID = AttributesEnum.ReversedVoucherId.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int SOURCEDOCUMENTSNO = AttributesEnum.SourceDocumentSno.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int PERIODSNO = AttributesEnum.PeriodSno.index();
    public static final int PERIODSTARTDATE = AttributesEnum.PeriodStartDate.index();
    public static final int PERIODENDDATE = AttributesEnum.PeriodEndDate.index();
    public static final int FISCALYEARSNO = AttributesEnum.FiscalYearSno.index();
    public static final int SOURCEDOCUMENTTYPE = AttributesEnum.SourceDocumentType.index();
    public static final int TEMPDEPARTMENTID = AttributesEnum.TempDepartmentId.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int REFERENCENO = AttributesEnum.ReferenceNo.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTVOUCHERTYPENAME = AttributesEnum.txtVoucherTypeName.index();
    public static final int TXTPERIODNAME = AttributesEnum.txtPeriodName.index();
    public static final int TXTPROJECTNAME = AttributesEnum.txtProjectName.index();
    public static final int TXTTEMPDEPARTMENTNAME = AttributesEnum.txtTempDepartmentName.index();
    public static final int VOUCHERCATEGORYSNO = AttributesEnum.VoucherCategorySno.index();
    public static final int TXTSUMDEBIT = AttributesEnum.txtSumDebit.index();
    public static final int TXTSUMCREDIT = AttributesEnum.txtSumCredit.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int YEARDIGIT = AttributesEnum.YearDigit.index();
    public static final int MONTHDIGIT = AttributesEnum.MonthDigit.index();
    public static final int VOUCHERNOPREFIX = AttributesEnum.VoucherNoPrefix.index();
    public static final int ISREVERSED = AttributesEnum.IsReversed.index();
    public static final int REVERSEFISCALYEARSNO = AttributesEnum.ReverseFiscalYearSno.index();
    public static final int REVERSEPERIODDATE = AttributesEnum.ReversePeriodDate.index();
    public static final int REVERSEPERIODSNO = AttributesEnum.ReversePeriodSno.index();
    public static final int REVERSEPERIODENDDATE = AttributesEnum.ReversePeriodEndDate.index();
    public static final int REVERSEPERIODSTARTDATE = AttributesEnum.ReversePeriodStartDate.index();
    public static final int REVERSEREASON = AttributesEnum.ReverseReason.index();
    public static final int TXTREVERSEVOUCHERCODE = AttributesEnum.txtReverseVoucherCode.index();
    public static final int REVERSEDVOUCHERCODE = AttributesEnum.ReversedVoucherCode.index();
    public static final int GLINSTALLMENTKNOCKOFF = AttributesEnum.GlInstallmentKnockoff.index();
    public static final int GLVOUCHERACCOUNTS = AttributesEnum.GlVoucherAccounts.index();
    public static final int GLVOUCHERTYPES = AttributesEnum.GlVoucherTypes.index();
    public static final int ADMINCOMPANY = AttributesEnum.AdminCompany.index();
    public static final int GLPERIODS = AttributesEnum.GlPeriods.index();
    public static final int GLPROJECTS = AttributesEnum.GlProjects.index();
    public static final int GLVOUCHERLINES = AttributesEnum.GlVoucherLines.index();
    public static final int ADMINCOMPANY1 = AttributesEnum.AdminCompany1.index();
    public static final int ACCGLPARAMETERVO = AttributesEnum.AccGlParameterVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlVoucherHeaderImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpfms.modelfms.fmseo.GlVoucherHeader");
    }


    /**
     * Gets the attribute value for VoucherHeaderSno, using the alias name VoucherHeaderSno.
     * @return the value of VoucherHeaderSno
     */
    public Integer getVoucherHeaderSno() {
        return (Integer) getAttributeInternal(VOUCHERHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherHeaderSno.
     * @param value value to set the VoucherHeaderSno
     */
    public void setVoucherHeaderSno(Integer value) {
        setAttributeInternal(VOUCHERHEADERSNO, value);
    }

    /**
     * Gets the attribute value for VoucherTypeId, using the alias name VoucherTypeId.
     * @return the value of VoucherTypeId
     */
    public Integer getVoucherTypeId() {
        return (Integer) getAttributeInternal(VOUCHERTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherTypeId.
     * @param value value to set the VoucherTypeId
     */
    public void setVoucherTypeId(Integer value) {
        setAttributeInternal(VOUCHERTYPEID, value);
    }

    /**
     * Gets the attribute value for VoucherHeaderCode, using the alias name VoucherHeaderCode.
     * @return the value of VoucherHeaderCode
     */
    public Long getVoucherHeaderCode() {
        return (Long) getAttributeInternal(VOUCHERHEADERCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherHeaderCode.
     * @param value value to set the VoucherHeaderCode
     */
    public void setVoucherHeaderCode(Long value) {
        setAttributeInternal(VOUCHERHEADERCODE, value);
    }

    /**
     * Gets the attribute value for VoucherDate, using the alias name VoucherDate.
     * @return the value of VoucherDate
     */
    public Timestamp getVoucherDate() {
        return (Timestamp) getAttributeInternal(VOUCHERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherDate.
     * @param value value to set the VoucherDate
     */
    public void setVoucherDate(Timestamp value) {
        setAttributeInternal(VOUCHERDATE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for BatchId, using the alias name BatchId.
     * @return the value of BatchId
     */
    public Integer getBatchId() {
        return (Integer) getAttributeInternal(BATCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchId.
     * @param value value to set the BatchId
     */
    public void setBatchId(Integer value) {
        setAttributeInternal(BATCHID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for SupervisedBy, using the alias name SupervisedBy.
     * @return the value of SupervisedBy
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedBy.
     * @param value value to set the SupervisedBy
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for SupervisedDate, using the alias name SupervisedDate.
     * @return the value of SupervisedDate
     */
    public Timestamp getSupervisedDate() {
        return (Timestamp) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedDate.
     * @param value value to set the SupervisedDate
     */
    public void setSupervisedDate(Timestamp value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IsSupervised, using the alias name IsSupervised.
     * @return the value of IsSupervised
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSupervised.
     * @param value value to set the IsSupervised
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for CurrencySno, using the alias name CurrencySno.
     * @return the value of CurrencySno
     */
    public Integer getCurrencySno() {
        return (Integer) getAttributeInternal(CURRENCYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrencySno.
     * @param value value to set the CurrencySno
     */
    public void setCurrencySno(Integer value) {
        setAttributeInternal(CURRENCYSNO, value);
    }

    /**
     * Gets the attribute value for ExchangeRate, using the alias name ExchangeRate.
     * @return the value of ExchangeRate
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExchangeRate.
     * @param value value to set the ExchangeRate
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for TempProjectId, using the alias name TempProjectId.
     * @return the value of TempProjectId
     */
    public Integer getTempProjectId() {
        return (Integer) getAttributeInternal(TEMPPROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TempProjectId.
     * @param value value to set the TempProjectId
     */
    public void setTempProjectId(Integer value) {
        setAttributeInternal(TEMPPROJECTID, value);
    }

    /**
     * Gets the attribute value for FileName, using the alias name FileName.
     * @return the value of FileName
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FileName.
     * @param value value to set the FileName
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for ReversedBy, using the alias name ReversedBy.
     * @return the value of ReversedBy
     */
    public Integer getReversedBy() {
        return (Integer) getAttributeInternal(REVERSEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversedBy.
     * @param value value to set the ReversedBy
     */
    public void setReversedBy(Integer value) {
        setAttributeInternal(REVERSEDBY, value);
    }

    /**
     * Gets the attribute value for ReversedDate, using the alias name ReversedDate.
     * @return the value of ReversedDate
     */
    public Timestamp getReversedDate() {
        return (Timestamp) getAttributeInternal(REVERSEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversedDate.
     * @param value value to set the ReversedDate
     */
    public void setReversedDate(Timestamp value) {
        setAttributeInternal(REVERSEDDATE, value);
    }

    /**
     * Gets the attribute value for ReversedVoucherId, using the alias name ReversedVoucherId.
     * @return the value of ReversedVoucherId
     */
    public Integer getReversedVoucherId() {
        return (Integer) getAttributeInternal(REVERSEDVOUCHERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversedVoucherId.
     * @param value value to set the ReversedVoucherId
     */
    public void setReversedVoucherId(Integer value) {
        setAttributeInternal(REVERSEDVOUCHERID, value);
    }

    /**
     * Gets the attribute value for UnSupervisedBy, using the alias name UnSupervisedBy.
     * @return the value of UnSupervisedBy
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedBy.
     * @param value value to set the UnSupervisedBy
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for UnSupervisedDate, using the alias name UnSupervisedDate.
     * @return the value of UnSupervisedDate
     */
    public Timestamp getUnSupervisedDate() {
        return (Timestamp) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedDate.
     * @param value value to set the UnSupervisedDate
     */
    public void setUnSupervisedDate(Timestamp value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for SourceDocumentSno, using the alias name SourceDocumentSno.
     * @return the value of SourceDocumentSno
     */
    public Integer getSourceDocumentSno() {
        return (Integer) getAttributeInternal(SOURCEDOCUMENTSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceDocumentSno.
     * @param value value to set the SourceDocumentSno
     */
    public void setSourceDocumentSno(Integer value) {
        setAttributeInternal(SOURCEDOCUMENTSNO, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }


    /**
     * Gets the attribute value for PeriodSno, using the alias name PeriodSno.
     * @return the value of PeriodSno
     */
    public Integer getPeriodSno() {
        return (Integer) getAttributeInternal(PERIODSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodSno.
     * @param value value to set the PeriodSno
     */
    public void setPeriodSno(Integer value) {
        setAttributeInternal(PERIODSNO, value);
    }

    /**
     * Gets the attribute value for PeriodStartDate, using the alias name PeriodStartDate.
     * @return the value of PeriodStartDate
     */
    public Timestamp getPeriodStartDate() {
        return (Timestamp) getAttributeInternal(PERIODSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodStartDate.
     * @param value value to set the PeriodStartDate
     */
    public void setPeriodStartDate(Timestamp value) {
        setAttributeInternal(PERIODSTARTDATE, value);
    }

    /**
     * Gets the attribute value for PeriodEndDate, using the alias name PeriodEndDate.
     * @return the value of PeriodEndDate
     */
    public Timestamp getPeriodEndDate() {
        return (Timestamp) getAttributeInternal(PERIODENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeriodEndDate.
     * @param value value to set the PeriodEndDate
     */
    public void setPeriodEndDate(Timestamp value) {
        setAttributeInternal(PERIODENDDATE, value);
    }

    /**
     * Gets the attribute value for FiscalYearSno, using the alias name FiscalYearSno.
     * @return the value of FiscalYearSno
     */
    public Integer getFiscalYearSno() {
        return (Integer) getAttributeInternal(FISCALYEARSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FiscalYearSno.
     * @param value value to set the FiscalYearSno
     */
    public void setFiscalYearSno(Integer value) {
        setAttributeInternal(FISCALYEARSNO, value);
    }

    /**
     * Gets the attribute value for SourceDocumentType, using the alias name SourceDocumentType.
     * @return the value of SourceDocumentType
     */
    public Integer getSourceDocumentType() {
        return (Integer) getAttributeInternal(SOURCEDOCUMENTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceDocumentType.
     * @param value value to set the SourceDocumentType
     */
    public void setSourceDocumentType(Integer value) {
        setAttributeInternal(SOURCEDOCUMENTTYPE, value);
    }

    /**
     * Gets the attribute value for TempDepartmentId, using the alias name TempDepartmentId.
     * @return the value of TempDepartmentId
     */
    public Integer getTempDepartmentId() {
        return (Integer) getAttributeInternal(TEMPDEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TempDepartmentId.
     * @param value value to set the TempDepartmentId
     */
    public void setTempDepartmentId(Integer value) {
        setAttributeInternal(TEMPDEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for LocationId, using the alias name LocationId.
     * @return the value of LocationId
     */
    public BigDecimal getLocationId() {
        return (BigDecimal) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationId.
     * @param value value to set the LocationId
     */
    public void setLocationId(BigDecimal value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for ReferenceNo, using the alias name ReferenceNo.
     * @return the value of ReferenceNo
     */
    public String getReferenceNo() {
        return (String) getAttributeInternal(REFERENCENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReferenceNo.
     * @param value value to set the ReferenceNo
     */
    public void setReferenceNo(String value) {
        setAttributeInternal(REFERENCENO, value);
    }

    /**
     * Gets the attribute value for GlobalCompanyId, using the alias name GlobalCompanyId.
     * @return the value of GlobalCompanyId
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompanyId.
     * @param value value to set the GlobalCompanyId
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for txtLocationName, using the alias name txtLocationName.
     * @return the value of txtLocationName
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtLocationName.
     * @param value value to set the txtLocationName
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for txtVoucherTypeName, using the alias name txtVoucherTypeName.
     * @return the value of txtVoucherTypeName
     */
    public String gettxtVoucherTypeName() {
        return (String) getAttributeInternal(TXTVOUCHERTYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtVoucherTypeName.
     * @param value value to set the txtVoucherTypeName
     */
    public void settxtVoucherTypeName(String value) {
        setAttributeInternal(TXTVOUCHERTYPENAME, value);
    }

    /**
     * Gets the attribute value for txtPeriodName, using the alias name txtPeriodName.
     * @return the value of txtPeriodName
     */
    public String gettxtPeriodName() {
        return (String) getAttributeInternal(TXTPERIODNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtPeriodName.
     * @param value value to set the txtPeriodName
     */
    public void settxtPeriodName(String value) {
        setAttributeInternal(TXTPERIODNAME, value);
    }

    /**
     * Gets the attribute value for txtProjectName, using the alias name txtProjectName.
     * @return the value of txtProjectName
     */
    public String gettxtProjectName() {
        return (String) getAttributeInternal(TXTPROJECTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtProjectName.
     * @param value value to set the txtProjectName
     */
    public void settxtProjectName(String value) {
        setAttributeInternal(TXTPROJECTNAME, value);
    }

    /**
     * Gets the attribute value for txtTempDepartmentName, using the alias name txtTempDepartmentName.
     * @return the value of txtTempDepartmentName
     */
    public String gettxtTempDepartmentName() {
        return (String) getAttributeInternal(TXTTEMPDEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtTempDepartmentName.
     * @param value value to set the txtTempDepartmentName
     */
    public void settxtTempDepartmentName(String value) {
        setAttributeInternal(TXTTEMPDEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for VoucherCategorySno, using the alias name VoucherCategorySno.
     * @return the value of VoucherCategorySno
     */
    public Integer getVoucherCategorySno() {
        return (Integer) getAttributeInternal(VOUCHERCATEGORYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherCategorySno.
     * @param value value to set the VoucherCategorySno
     */
    public void setVoucherCategorySno(Integer value) {
        setAttributeInternal(VOUCHERCATEGORYSNO, value);
    }

    /**
     * Gets the attribute value for txtSumDebit, using the alias name txtSumDebit.
     * @return the value of txtSumDebit
     */
    public BigDecimal gettxtSumDebit() {
        return (BigDecimal) getAttributeInternal(TXTSUMDEBIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtSumDebit.
     * @param value value to set the txtSumDebit
     */
    public void settxtSumDebit(BigDecimal value) {
        setAttributeInternal(TXTSUMDEBIT, value);
    }

    /**
     * Gets the attribute value for txtSumCredit, using the alias name txtSumCredit.
     * @return the value of txtSumCredit
     */
    public BigDecimal gettxtSumCredit() {
        return (BigDecimal) getAttributeInternal(TXTSUMCREDIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtSumCredit.
     * @param value value to set the txtSumCredit
     */
    public void settxtSumCredit(BigDecimal value) {
        setAttributeInternal(TXTSUMCREDIT, value);
    }

    /**
     * Gets the attribute value for IsUnsupervised, using the alias name IsUnsupervised.
     * @return the value of IsUnsupervised
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsUnsupervised.
     * @param value value to set the IsUnsupervised
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for YearDigit, using the alias name YearDigit.
     * @return the value of YearDigit
     */
    public Integer getYearDigit() {
        return (Integer) getAttributeInternal(YEARDIGIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for YearDigit.
     * @param value value to set the YearDigit
     */
    public void setYearDigit(Integer value) {
        setAttributeInternal(YEARDIGIT, value);
    }

    /**
     * Gets the attribute value for MonthDigit, using the alias name MonthDigit.
     * @return the value of MonthDigit
     */
    public String getMonthDigit() {
        return (String) getAttributeInternal(MONTHDIGIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for MonthDigit.
     * @param value value to set the MonthDigit
     */
    public void setMonthDigit(String value) {
        setAttributeInternal(MONTHDIGIT, value);
    }

    /**
     * Gets the attribute value for VoucherNoPrefix, using the alias name VoucherNoPrefix.
     * @return the value of VoucherNoPrefix
     */
    public Integer getVoucherNoPrefix() {
        return (Integer) getAttributeInternal(VOUCHERNOPREFIX);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherNoPrefix.
     * @param value value to set the VoucherNoPrefix
     */
    public void setVoucherNoPrefix(Integer value) {
        setAttributeInternal(VOUCHERNOPREFIX, value);
    }

    /**
     * Gets the attribute value for IsReversed, using the alias name IsReversed.
     * @return the value of IsReversed
     */
    public String getIsReversed() {
        return (String) getAttributeInternal(ISREVERSED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsReversed.
     * @param value value to set the IsReversed
     */
    public void setIsReversed(String value) {
        setAttributeInternal(ISREVERSED, value);
    }

    /**
     * Gets the attribute value for ReverseFiscalYearSno, using the alias name ReverseFiscalYearSno.
     * @return the value of ReverseFiscalYearSno
     */
    public Integer getReverseFiscalYearSno() {
        return (Integer) getAttributeInternal(REVERSEFISCALYEARSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReverseFiscalYearSno.
     * @param value value to set the ReverseFiscalYearSno
     */
    public void setReverseFiscalYearSno(Integer value) {
        setAttributeInternal(REVERSEFISCALYEARSNO, value);
    }

    /**
     * Gets the attribute value for ReversePeriodDate, using the alias name ReversePeriodDate.
     * @return the value of ReversePeriodDate
     */
    public Timestamp getReversePeriodDate() {
        return (Timestamp) getAttributeInternal(REVERSEPERIODDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversePeriodDate.
     * @param value value to set the ReversePeriodDate
     */
    public void setReversePeriodDate(Timestamp value) {
        setAttributeInternal(REVERSEPERIODDATE, value);
    }

    /**
     * Gets the attribute value for ReversePeriodSno, using the alias name ReversePeriodSno.
     * @return the value of ReversePeriodSno
     */
    public Integer getReversePeriodSno() {
        return (Integer) getAttributeInternal(REVERSEPERIODSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversePeriodSno.
     * @param value value to set the ReversePeriodSno
     */
    public void setReversePeriodSno(Integer value) {
        setAttributeInternal(REVERSEPERIODSNO, value);
    }

    /**
     * Gets the attribute value for ReversePeriodEndDate, using the alias name ReversePeriodEndDate.
     * @return the value of ReversePeriodEndDate
     */
    public Timestamp getReversePeriodEndDate() {
        return (Timestamp) getAttributeInternal(REVERSEPERIODENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversePeriodEndDate.
     * @param value value to set the ReversePeriodEndDate
     */
    public void setReversePeriodEndDate(Timestamp value) {
        setAttributeInternal(REVERSEPERIODENDDATE, value);
    }

    /**
     * Gets the attribute value for ReversePeriodStartDate, using the alias name ReversePeriodStartDate.
     * @return the value of ReversePeriodStartDate
     */
    public Timestamp getReversePeriodStartDate() {
        return (Timestamp) getAttributeInternal(REVERSEPERIODSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversePeriodStartDate.
     * @param value value to set the ReversePeriodStartDate
     */
    public void setReversePeriodStartDate(Timestamp value) {
        setAttributeInternal(REVERSEPERIODSTARTDATE, value);
    }

    /**
     * Gets the attribute value for ReverseReason, using the alias name ReverseReason.
     * @return the value of ReverseReason
     */
    public String getReverseReason() {
        return (String) getAttributeInternal(REVERSEREASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReverseReason.
     * @param value value to set the ReverseReason
     */
    public void setReverseReason(String value) {
        setAttributeInternal(REVERSEREASON, value);
    }


    /**
     * Gets the attribute value for txtReverseVoucherCode, using the alias name txtReverseVoucherCode.
     * @return the value of txtReverseVoucherCode
     */
    public Long gettxtReverseVoucherCode() {
        return (Long) getAttributeInternal(TXTREVERSEVOUCHERCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtReverseVoucherCode.
     * @param value value to set the txtReverseVoucherCode
     */
    public void settxtReverseVoucherCode(Long value) {
        setAttributeInternal(TXTREVERSEVOUCHERCODE, value);
    }

    /**
     * Gets the attribute value for ReversedVoucherCode, using the alias name ReversedVoucherCode.
     * @return the value of ReversedVoucherCode
     */
    public Long getReversedVoucherCode() {
        return (Long) getAttributeInternal(REVERSEDVOUCHERCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversedVoucherCode.
     * @param value value to set the ReversedVoucherCode
     */
    public void setReversedVoucherCode(Long value) {
        setAttributeInternal(REVERSEDVOUCHERCODE, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getGlInstallmentKnockoff() {
        return (RowIterator) getAttributeInternal(GLINSTALLMENTKNOCKOFF);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getGlVoucherAccounts() {
        return (RowIterator) getAttributeInternal(GLVOUCHERACCOUNTS);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public GlVoucherTypesImpl getGlVoucherTypes() {
        return (GlVoucherTypesImpl) getAttributeInternal(GLVOUCHERTYPES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setGlVoucherTypes(GlVoucherTypesImpl value) {
        setAttributeInternal(GLVOUCHERTYPES, value);
    }

    /**
     * @return the associated entity erpadm.modeladm.admeo.AdminCompanyImpl.
     */
    public AdminCompanyImpl getAdminCompany() {
        return (AdminCompanyImpl) getAttributeInternal(ADMINCOMPANY);
    }

    /**
     * Sets <code>value</code> as the associated entity erpadm.modeladm.admeo.AdminCompanyImpl.
     */
    public void setAdminCompany(AdminCompanyImpl value) {
        setAttributeInternal(ADMINCOMPANY, value);
    }

    /**
     * @return the associated entity GlPeriodsImpl.
     */
    public GlPeriodsImpl getGlPeriods() {
        return (GlPeriodsImpl) getAttributeInternal(GLPERIODS);
    }

    /**
     * Sets <code>value</code> as the associated entity GlPeriodsImpl.
     */
    public void setGlPeriods(GlPeriodsImpl value) {
        setAttributeInternal(GLPERIODS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getGlProjects() {
        return (EntityImpl) getAttributeInternal(GLPROJECTS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setGlProjects(EntityImpl value) {
        setAttributeInternal(GLPROJECTS, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getGlVoucherLines() {
        return (RowIterator) getAttributeInternal(GLVOUCHERLINES);
    }


    /**
     * @return the associated entity erpadm.modeladm.admeo.AdminCompanyImpl.
     */
    public AdminCompanyImpl getAdminCompany1() {
        return (AdminCompanyImpl) getAttributeInternal(ADMINCOMPANY1);
    }

    /**
     * Sets <code>value</code> as the associated entity erpadm.modeladm.admeo.AdminCompanyImpl.
     */
    public void setAdminCompany1(AdminCompanyImpl value) {
        setAttributeInternal(ADMINCOMPANY1, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccGlParameterVO.
     */
    public RowSet getAccGlParameterVO() {
        return (RowSet) getAttributeInternal(ACCGLPARAMETERVO);
    }


    /**
     * @param voucherHeaderSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer voucherHeaderSno) {
        return new Key(new Object[] { voucherHeaderSno });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT ) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "VOUCHER_HEADER_SNO",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(VOUCHERHEADERSNO,  Integer.parseInt(result));
          
           //setVoucherHeaderSno(Integer.parseInt(result));
           //setVoucherHeaderSno(Integer.parseInt(result));
           
           //getting the year format mask for number sequence
           getAccGlParameterVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "VOUCHER_NO_PREFIX");
           getAccGlParameterVO().setNamedWhereClauseParam("P_ADF_COMPANY_ID", getCompanyId());
           getAccGlParameterVO().setNamedWhereClauseParam("P_ADF_GLOBAL_COMPANY_ID", getGlobalCompanyId());
           getAccGlParameterVO().executeQuery();
           
           String erpprefix = getAccGlParameterVO().first().getAttribute("ParameterValue").toString();
           if (!erpprefix.equals("N")) {
                SimpleDateFormat erpFormat = new SimpleDateFormat(erpprefix);
                populateAttributeAsChanged(VOUCHERNOPREFIX, Integer.parseInt(erpFormat.format(getVoucherDate())));
            }
            
           //voucher no length
           getAccGlParameterVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "VOUCHER_NO_LPAD");
           getAccGlParameterVO().executeQuery();
           
           String erpvoucherlength= getAccGlParameterVO().first().getAttribute("ParameterValue").toString();
            
           ///fiscal year reset value
           getAccGlParameterVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "RESET_VOUCH_ON_FY");
           getAccGlParameterVO().executeQuery();
           String erpfyreset=getAccGlParameterVO().first().getAttribute("ParameterValue").toString();
           
           
           ////location reset value
           getAccGlParameterVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "RESET_VOUCH_ON_LOC");
           getAccGlParameterVO().executeQuery();
           String erplocreset=getAccGlParameterVO().first().getAttribute("ParameterValue").toString();
           
          // System.out.println("getNamedWhereClauseParams"+getAccGlParameterVO().getNamedWhereClauseParams().getAttributeValues());
           
          //copmany reset
           getAccGlParameterVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "RESET_VOUCH_ON_COMP");
           getAccGlParameterVO().executeQuery();
           String erpcompreset=getAccGlParameterVO().first().getAttribute("ParameterValue").toString();
           
            
           //voucher type reset
           getAccGlParameterVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "RESET_VOUCH_ON_VTYPE");
           getAccGlParameterVO().executeQuery();
           String erpvtypereset=getAccGlParameterVO().first().getAttribute("ParameterValue").toString();
           
           //period reset value
           getAccGlParameterVO().setNamedWhereClauseParam("P_ADF_PARAMETER_ID", "RESET_VOUCH_ON_PER");
           getAccGlParameterVO().executeQuery();
           String erpperiodreset=getAccGlParameterVO().first().getAttribute("ParameterValue").toString();
           
           String sqlvoucher=" where global_company_id="+getGlobalCompanyId();
          
           if (erpvtypereset.equals("Y")) {
                sqlvoucher=sqlvoucher +" and VOUCHER_TYPE_ID="+getVoucherTypeId();
           }
            
           if (erpcompreset.equals("Y")) {
                sqlvoucher=sqlvoucher +" and company_id="+getCompanyId();
           }
           
           if (erpfyreset.equals("Y")) {
                sqlvoucher=sqlvoucher +" and fiscal_year_sno="+getFiscalYearSno();
           }
           
           
           if (erpperiodreset.equals("Y")) {
                sqlvoucher=sqlvoucher +" and period_sno="+getPeriodSno();
           }
           
           
           if (erplocreset.equals("Y")) {
                sqlvoucher=sqlvoucher +" and location_id="+getLocationId();
           }
           sqlvoucher="select coalesce(max(VOUCHER_HEADER_CODE),0)+1 from gl_voucher_header "+sqlvoucher;
           
          // System.out.println("this is query>>"+sqlvoucher);
           result = ERPGlobalPLSQLClass.doExecuteSQLQueryModel(getDBTransaction(), sqlvoucher);
           if (!erpprefix.equals("N") && result.equals("1")) {//in case prefix is allowed then
           populateAttributeAsChanged(VOUCHERHEADERCODE, Long.parseLong(getVoucherNoPrefix()+erpvoucherlength+result) );
           }
           else
           {
           populateAttributeAsChanged(VOUCHERHEADERCODE, Long.parseLong(result) );
           }
          // System.out.println(" voucher header ");
       }
        if (operation==DML_UPDATE) {
            if (getIsReversed()!=null && getIsReversed().equals("Y")) {
             ViewObject vo=getDBTransaction().getRootApplicationModule().findViewObject("GlVoucherHeaderForReverseCRUD");
               Row reverseVoucher=vo.createRow();
               reverseVoucher.setAttribute(LOCATIONID, getLocationId());
               reverseVoucher.setAttribute(COMPANYID, getCompanyId());
               reverseVoucher.setAttribute(PERIODSNO, getReversePeriodSno());
               reverseVoucher.setAttribute(VOUCHERDATE, getReversePeriodDate());
               reverseVoucher.setAttribute(PERIODSTARTDATE, getReversePeriodStartDate());
               reverseVoucher.setAttribute(PERIODENDDATE, getReversePeriodEndDate());
               reverseVoucher.setAttribute(VOUCHERTYPEID, getVoucherTypeId());
               reverseVoucher.setAttribute(TEMPPROJECTID, getTempProjectId());
               reverseVoucher.setAttribute(TEMPDEPARTMENTID, getTempDepartmentId());
               reverseVoucher.setAttribute(REMARKS, "Reversal Of Voucher:"+getVoucherHeaderCode()+","+getRemarks()+","+getReverseReason());
               reverseVoucher.setAttribute(REVERSEDVOUCHERID, getVoucherHeaderSno());
               reverseVoucher.setAttribute(BATCHID, getBatchId());
               reverseVoucher.setAttribute(ISSUPERVISED, "Y");
               reverseVoucher.setAttribute(REVERSEDVOUCHERCODE, getVoucherHeaderCode());
               vo.insertRow(reverseVoucher);
               vo.setCurrentRow(reverseVoucher);
               vo=getDBTransaction().getRootApplicationModule().findViewObject("GlVoucherLinesForReverseDetCRUD");
               RowIterator rsi=getGlVoucherLines();
               while(rsi.hasNext()) {
                   Row detRow=rsi.next();
                   Row detreverseVoucher=vo.createRow();
                   detreverseVoucher.setAttribute("ChartOfAccountId", detRow.getAttribute("ChartOfAccountId"));
                   detreverseVoucher.setAttribute("Credit", detRow.getAttribute("Debit"));
                   detreverseVoucher.setAttribute("Debit", detRow.getAttribute("Credit"));
                   detreverseVoucher.setAttribute("Naration", detRow.getAttribute("Naration"));
                   detreverseVoucher.setAttribute("ProjectSno", detRow.getAttribute("ProjectSno"));
                   detreverseVoucher.setAttribute("DepartmentId", detRow.getAttribute("DepartmentId"));
                   vo.insertRow(detreverseVoucher);
               }
           }
       }
        super.doDML(operation, e);
        
        if (operation==DML_UPDATE) {
           try {
               ViewObject vo =
                   getDBTransaction().getRootApplicationModule().findViewObject("GlVoucherHeaderForReverseCRUD");
               //settxtReverseVoucherCode((Long) vo.getCurrentRow().getAttribute("VoucherHeaderCode"));
               System.out.println(vo.getCurrentRow().getAttribute("VoucherHeaderCode")+ "<<that is code");
               populateAttributeAsChanged(TXTREVERSEVOUCHERCODE, vo.getCurrentRow().getAttribute("VoucherHeaderCode"));
               System.out.println(gettxtReverseVoucherCode()+ " getter voucher code reversal");
           } catch (Exception ex) {
               // TODO: Add catch code
              // ex.printStackTrace();
           }
       }
    }
    @Override
    public void afterCommit(TransactionEvent transactionEvent) {

        

         // TODO Implement this method
       // ApplicationModule am=getDBTransaction().getRootApplicationModule();
       // ViewObject vo=am.findViewObject("GlVoucherLinesDETCRUD");
       // vo.executeQuery();
        //System.out.println("gl header after commit");
        super.afterCommit(transactionEvent);
    }
    
}

