package erpfms.modelfms.fmsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 04 15:30:45 PKT 2021
// ---------------------------------------------------------------------
public interface GlBankBranchVO extends ViewObject {
    void executeEmptyRowSet();
}

