package erpfms.modelfms.fmsvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 30 00:27:17 PKT 2020
// ---------------------------------------------------------------------
public interface GlFiscalYearVORow extends Row {
    void doErpGenerateFYPeriods();
}

