package erpfms.modelfms.fmsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 26 17:55:32 PKT 2020
// ---------------------------------------------------------------------
public interface GlVoucherLinesVO extends ViewObject {
    void executeEmptyRowSet();
}

