package erpfms.modelfms.fmsqvo;


import erpfms.modelfms.fmsqvo.common.GlPeriodForUserRightsQVORow;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 16 15:54:49 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GlPeriodForUserRightsQVORowImpl extends ViewRowImpl implements GlPeriodForUserRightsQVORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PeriodSno,
        PeriodName,
        FiscalYearSno,
        YearDescription,
        FiscalYearr,
        IsAdjustment,
        IsClosed,
        QuarterNo,
        StartDate,
        EndDate,
        CompanyId,
        txtSelected;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PERIODSNO = AttributesEnum.PeriodSno.index();
    public static final int PERIODNAME = AttributesEnum.PeriodName.index();
    public static final int FISCALYEARSNO = AttributesEnum.FiscalYearSno.index();
    public static final int YEARDESCRIPTION = AttributesEnum.YearDescription.index();
    public static final int FISCALYEARR = AttributesEnum.FiscalYearr.index();
    public static final int ISADJUSTMENT = AttributesEnum.IsAdjustment.index();
    public static final int ISCLOSED = AttributesEnum.IsClosed.index();
    public static final int QUARTERNO = AttributesEnum.QuarterNo.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int TXTSELECTED = AttributesEnum.txtSelected.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GlPeriodForUserRightsQVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PeriodSno.
     * @return the PeriodSno
     */
    public Integer getPeriodSno() {
        return (Integer) getAttributeInternal(PERIODSNO);
    }

    /**
     * Gets the attribute value for the calculated attribute PeriodName.
     * @return the PeriodName
     */
    public String getPeriodName() {
        return (String) getAttributeInternal(PERIODNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute FiscalYearSno.
     * @return the FiscalYearSno
     */
    public Integer getFiscalYearSno() {
        return (Integer) getAttributeInternal(FISCALYEARSNO);
    }

    /**
     * Gets the attribute value for the calculated attribute YearDescription.
     * @return the YearDescription
     */
    public String getYearDescription() {
        return (String) getAttributeInternal(YEARDESCRIPTION);
    }

    /**
     * Gets the attribute value for the calculated attribute FiscalYearr.
     * @return the FiscalYearr
     */
    public Integer getFiscalYearr() {
        return (Integer) getAttributeInternal(FISCALYEARR);
    }

    /**
     * Gets the attribute value for the calculated attribute IsAdjustment.
     * @return the IsAdjustment
     */
    public String getIsAdjustment() {
        return (String) getAttributeInternal(ISADJUSTMENT);
    }

    /**
     * Gets the attribute value for the calculated attribute IsClosed.
     * @return the IsClosed
     */
    public String getIsClosed() {
        return (String) getAttributeInternal(ISCLOSED);
    }

    /**
     * Gets the attribute value for the calculated attribute QuarterNo.
     * @return the QuarterNo
     */
    public Integer getQuarterNo() {
        return (Integer) getAttributeInternal(QUARTERNO);
    }

    /**
     * Gets the attribute value for the calculated attribute StartDate.
     * @return the StartDate
     */
    public Timestamp getStartDate() {
        return (Timestamp) getAttributeInternal(STARTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute EndDate.
     * @return the EndDate
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyId.
     * @return the CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSelected.
     * @return the txtSelected
     */
    public String gettxtSelected() {
        return (String) getAttributeInternal(TXTSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtSelected.
     * @param value value to set the  txtSelected
     */
    public void settxtSelected(String value) {
        setAttributeInternal(TXTSELECTED, value);
    }
    
    public void doErpAssignSinglePeriodToUser() {
            ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("GlUserClosedPeriodRightDetCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("CompanyId", getCompanyId());
            cr.setAttribute("FiscalYearSno", getFiscalYearSno());
            cr.setAttribute("PeriodSno", getPeriodSno());
            cr.setAttribute("UserId", getDBTransaction().getRootApplicationModule().findViewObject("SysUsersByUserIdRO").first().getAttribute("UserId"));
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    }   
}

