package erpfms.modelfms.fmsqvo;


import erpfms.modelfms.fmsqvo.common.SysUsersForAssignCOAUserRightsQVORow;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 09 11:55:20 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysUsersForAssignCOAUserRightsQVORowImpl extends ViewRowImpl implements SysUsersForAssignCOAUserRightsQVORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserId,
        UserName,
        UserCode,
        txtSelected;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERID = AttributesEnum.UserId.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int USERCODE = AttributesEnum.UserCode.index();
    public static final int TXTSELECTED = AttributesEnum.txtSelected.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysUsersForAssignCOAUserRightsQVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public Integer getUserId() {
        return (Integer) getAttributeInternal(USERID);
    }

    /**
     * Gets the attribute value for the calculated attribute UserName.
     * @return the UserName
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute UserCode.
     * @return the UserCode
     */
    public String getUserCode() {
        return (String) getAttributeInternal(USERCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSelected.
     * @return the txtSelected
     */
    public String gettxtSelected() {
        return (String) getAttributeInternal(TXTSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtSelected.
     * @param value value to set the  txtSelected
     */
    public void settxtSelected(String value) {
        setAttributeInternal(TXTSELECTED, value);
    }

    public void doErpAssignSingleUserToCOA() {
            ViewObject vo = getDBTransaction().getRootApplicationModule().findViewObject("GlCoaUserCompanyCRUD");
            Row cr = vo.createRow();
            cr.setAttribute("CompanyId", getDBTransaction().getRootApplicationModule().findViewObject("AdminCompanyVOByCompanyRO").first().getAttribute("CompCode"));
            cr.setAttribute("IsActive", "Y");
            cr.setAttribute("UserId", getUserId());
            //cr.setAttribute("Remarks", "Copied" + getModuleAction());
            settxtSelected("Y");
            vo.insertRow(cr);
            getDBTransaction().commit();
            //getDBTransaction().rollback();
        vo.clearCache();
        vo.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    }

}

