package erpfms.modelfms.fmsqvo;

import erpfms.modelfms.fmsqvo.common.SysUsersForAssignCOAUserRightsQVO;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 09 13:47:35 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysUsersForAssignCOAUserRightsQVOImpl extends ViewObjectImpl implements SysUsersForAssignCOAUserRightsQVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SysUsersForAssignCOAUserRightsQVOImpl() {
    }

    /**
     * Returns the bind variable value for P_ADF_GLOBAL_COMPANY_ID.
     * @return bind variable value for P_ADF_GLOBAL_COMPANY_ID
     */
    public Integer getP_ADF_GLOBAL_COMPANY_ID() {
        return (Integer) getNamedWhereClauseParam("P_ADF_GLOBAL_COMPANY_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_GLOBAL_COMPANY_ID.
     * @param value value to bind as P_ADF_GLOBAL_COMPANY_ID
     */
    public void setP_ADF_GLOBAL_COMPANY_ID(Integer value) {
        setNamedWhereClauseParam("P_ADF_GLOBAL_COMPANY_ID", value);
    }

    /**
     * Returns the bind variable value for P_ADF_COMPANY_ID.
     * @return bind variable value for P_ADF_COMPANY_ID
     */
    public Integer getP_ADF_COMPANY_ID() {
        return (Integer) getNamedWhereClauseParam("P_ADF_COMPANY_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_COMPANY_ID.
     * @param value value to bind as P_ADF_COMPANY_ID
     */
    public void setP_ADF_COMPANY_ID(Integer value) {
        setNamedWhereClauseParam("P_ADF_COMPANY_ID", value);
    }
 
    public void doErpAssignAllUserToCOA() {
        ViewObject vo = getRootApplicationModule().findViewObject("GlCoaUserCompanyCRUD");
        RowSetIterator rsi =this.getRowSet();
        rsi.setRangeSize(-1);
        for (int i=0;i<rsi.getRowCount();i++) {
            Row r = rsi.getRowAtRangeIndex(i);
            //record might be assigned through single assignment
            if (r.getAttribute("txtSelected")== null || r.getAttribute("txtSelected").toString().equals("N")) {
                r.setAttribute("txtSelected", "Y");
                Row cr = vo.createRow();
                cr.setAttribute("CompanyId", getDBTransaction().getRootApplicationModule().findViewObject("AdminCompanyVOByCompanyRO").first().getAttribute("CompCode"));
                cr.setAttribute("IsActive", "Y");
                cr.setAttribute("UserId", r.getAttribute("UserId"));
                vo.insertRow(cr);
            }
        }
        getDBTransaction().commit();
        vo.executeQuery();
        this.executeQuery();
        //executeQuery();
        //getDBTransaction().rollback();        
    }   
}

